In [18]:
import pandas as pd

df = pd.read_csv("data/coches-de-segunda-mano-sample.csv")
df.head()

,url,company,make,model,version,price,price_financed,fuel,year,kms,...,doors,shift,color,photos,is_professional,dealer,province,country,publish_date,insert_date
0,e158ae0ca53119ca199c28c36b5c2fcd,9881bcdd5a0ad4733037b3fb25e69c3a,SEAT,Toledo,SEAT Toledo 4p.,950,NaN,Diésel,2000.0,227000,...,4,Manual,Verde,5,False,0f4bb8455d27349b8273109b66a847f3,Navarra,Spain,2020-12-18 10:47:13,2021-01-15 00:00:00
1,ff267ebb7e700246f47f84f3db660b4b,9881bcdd5a0ad4733037b3fb25e69c3a,CITROEN,C1,CITROEN C1 PureTech 60KW 82CV Feel 5p.,6200,NaN,Gasolina,2017.0,50071,...,5,Manual,Blanco,6,True,Autos Raymara,Tenerife,Spain,2021-01-02 11:25:40,2021-01-15 00:00:00
2,de4b02db28ea7786c622b969be10c7c7,9881bcdd5a0ad4733037b3fb25e69c3a,FORD,Transit Connect,FORD Transit Connect Van 1.5 TDCi 100cv Ambien...,7851,7024.0,Diésel,2016.0,103000,...,4,Manual,Blanco,10,True,Auto 96,Barcelona,Spain,2020-12-16 10:51:45,2021-01-15 00:00:00
3,0449972a4d07594acf92e9a7dd28b39c,9881bcdd5a0ad4733037b3fb25e69c3a,VOLKSWAGEN,Caravelle,VOLKSWAGEN Caravelle Largo 2.0 TDI 140 Comfort...,19426,NaN,Diésel,2014.0,120000,...,4,Manual,Blanco,9,True,Inniauto,Navarra,Spain,2020-11-25 11:09:14,2021-01-15 00:00:00
4,12c4fa49bd4fdf23f19ecf396d3f02ef,9881bcdd5a0ad4733037b3fb25e69c3a,FORD,Transit,FORD Transit 350 96kW L4 Ambiente Propulsion T...,22850,22800.0,Diésel,2017.0,107000,...,2,Manual,Blanco,4,True,"Autofleet España,s.l",Sevilla,Spain,2021-01-12 20:00:34,2021-01-15 00:00:00

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   url              50000 non-null  object
 1   company          50000 non-null  object
 2   make             49998 non-null  object
 3   model            49995 non-null  object
 4   version          50000 non-null  object
 5   price            50000 non-null  int64
 6   price_financed   23563 non-null  float64
 7   fuel             49954 non-null  object
 8   year             49998 non-null  float64
 9   kms              50000 non-null  int64
 10  power            41472 non-null  float64
 11  doors            50000 non-null  int64
 12  shift            49889 non-null  object
 13  color            49406 non-null  object
 14  photos           50000 non-null  int64
 15  is_professional  50000 non-null  bool
 16  dealer           50000 non-null  object
 17  province         49994 non-null  object
 18  country          50000 non-null  object
 19  publish_date     50000 non-null  object
 20  insert_date      50000 non-null  object
dtypes: bool(1), float64(3), int64(4), object(13)
memory usage: 7.7+ MB

In [10]:
df.drop(columns = ["url"], inplace = True)

In [20]:
df = df.dropna(axis = 1)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   url              50000 non-null  object
 1   company          50000 non-null  object
 2   version          50000 non-null  object
 3   price            50000 non-null  int64
 4   kms              50000 non-null  int64
 5   doors            50000 non-null  int64
 6   photos           50000 non-null  int64
 7   is_professional  50000 non-null  bool
 8   dealer           50000 non-null  object
 9   country          50000 non-null  object
 10  publish_date     50000 non-null  object
 11  insert_date      50000 non-null  object
dtypes: bool(1), int64(4), object(7)
memory usage: 4.2+ MB

In [14]:
df["price_financed"].fillna(df["price_financed"].mean())

0        18480.029283
1        18480.029283
2         7024.000000
3        18480.029283
4        22800.000000
             ...
49995    16490.000000
49996    13551.000000
49997     9000.000000
49998    18480.029283
49999    18480.029283
Name: price_financed, Length: 50000, dtype: float64

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   company          50000 non-null  object
 1   make             49998 non-null  object
 2   model            49995 non-null  object
 3   version          50000 non-null  object
 4   price            50000 non-null  int64
 5   price_financed   23563 non-null  float64
 6   fuel             49954 non-null  object
 7   year             49998 non-null  float64
 8   kms              50000 non-null  int64
 9   power            41472 non-null  float64
 10  doors            50000 non-null  int64
 11  shift            49889 non-null  object
 12  color            49406 non-null  object
 13  photos           50000 non-null  int64
 14  is_professional  50000 non-null  bool
 15  dealer           50000 non-null  object
 16  province         49994 non-null  object
 17  country          50000 non-null  object
 18  publish_date     50000 non-null  object
 19  insert_date      50000 non-null  object
dtypes: bool(1), float64(3), int64(4), object(12)
memory usage: 7.3+ MB

# _____________________________________________________________-

In [8]:
x = df[["make", "model", "price"]]
x

             make            model  price
0            SEAT           Toledo    950
1         CITROEN               C1   6200
2            FORD  Transit Connect   7851
3      VOLKSWAGEN        Caravelle  19426
4            FORD          Transit  22850
...           ...              ...    ...
49995     HYUNDAI              i30  18490
49996     RENAULT           Laguna  14500
49997     PEUGEOT              108  11000
49998        AUDI              RS4  47900
49999     CITROEN               C2   2790

[50000 rows x 3 columns]

In [9]:
x.describe()

               price
count   50000.000000
mean    15166.270260
std     16485.669747
min       300.000000
25%      5500.000000
50%     11750.000000
75%     19800.000000
max    549900.000000