# Obtención de Datos Mediante APIs en Python

Alguna de las formas de obtención de datos es a través de **APIs (Application Programming Interfaces)**. Las APIs son una forma eficiente de acceder a datos y servicios en línea. Aprenderemos a realizar solicitudes a través de Python utilizando la popular biblioteca `requests`.

## Introducción a las APIs

Una API (Application Programming Interface) es un conjunto de reglas y protocolos que permiten a diferentes aplicaciones interactuar entre sí. Las APIs permiten a las aplicaciones solicitar datos o realizar acciones en un servidor remoto de manera estructurada y estandarizada.

![imagen](./img/http.PNG)

## Protocolo HTTP

El Protocolo de Transferencia de Hipertexto (HTTP) es el protocolo subyacente utilizado en la World Wide Web. Se utiliza para solicitar y transmitir datos en la web. 

![imagen](./img/peticion_respuesta.PNG)

Aquí tienes un ejemplo de arquitectura:

![imagen](./img/arquitectura_servidor.PNG)

Las solicitudes HTTP se pueden realizar utilizando varios métodos, siendo los más comunes:

* **GET**: Para recuperar datos.
* **POST**: Para enviar datos al servidor.
* **PUT**: Para actualizar datos en el servidor.
* **DELETE**: Para eliminar datos en el servidor.


![imagen](./img/documentacion_api.PNG)

Podemos hacer una petición:

![imagen](./img/parametros.PNG)

y obtener como respuesta diferentes códigos:

![imagen](./img/status_codes.PNG)

## Biblioteca ``requests``

La biblioteca requests es una de las más populares para realizar solicitudes HTTP en Python. Permite enviar solicitudes y procesar respuestas de una manera sencilla y eficiente.

In [26]:
# pip install requests

In [1]:
# Importamos librerias
import requests
import zipfile
import pandas as pd

## Primera petición

In [18]:
url = "https://yt3.googleusercontent.com/wqWZ8SXmktP5ROcvTxW2lGXskpwd2rZkthLaau8pZhJapVXOdLHLNvPkVnuy3waAp-nd7zwddQ=s900-c-k-c0x00ffffff-no-rj"
image = requests.get(url)

In [19]:
image

In [20]:
print(image.content)

b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x00\x00\x01\x00\x01\x00\x00\xff\xdb\x00\x84\x00\x03\x02\x02\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\n\x08\x08\x08\x08\n\n\n\x08\x08\x0b\r\n\x08\r\x08\x08\n\x08\x01\x03\x04\x04\x06\x05\x06\n\x06\x06\n\r\r\n\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\xff\xc0\x00\x11\x08\x03\x84\x03\x84\x03\x01"\x00\x02\x11\x01\x03\x11\x01\xff\xc4\x00\x1e\x00\x00\x02\x03\x00\x03\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x02\x03\x00\x01\x04\x05\x08\t\x07\x06\n\xff\xc4\x00`\x10\x01\x00\x02\x01\x03\x02\x03\x05\x04\x06\x08\x01\x07\x07\x00\x1b\x01\x02\x11!\x00\x03\x121A\x04"Q\x05\x132aqB\x81\x91\xf0\x06\x08\t\xa1\xb1\xc1\x07\x14\x15#R\xd1\xe1\xf1b\x16$%3Ur\x94\x18\x19&4DS\x82\xd35CT\x92\x93\xb3\xc4Est\xa2\xb2Fcde\xa3\xb4Vu\x83\x84\xc2\xd2\xd46\xff\xc4\x00\x1d\x01\x00\x03\x01\x01\x01\x01\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x02\x03\x01\x04\x05\x06\x08\x07\t\xff\xc4\x00K\x11\x01\x00\x01\x02\x02\x05\x05\n\n\t\x03\x05\x00\x03\x00\x00\x00\x01\x02\x11\x03\x12\x04\x05!1\xf0\x06AQq\xb1\x132Sa\x81\x91\x92\xa1\xb2\xd1"35Rrs\x82\xb3\xc1\xd2\x07\x14\x154T\x83\xa2\xe1\xf1#Bb\x16%Cc\x93$D\xc2\xff\xda\x00\x0c\x03\x01\x00\x02\x11\x03\x11\x00?\x00\xf2\xabSSS@MMMM\x015554\x04\xd4\xd4\xd4\xd0\x13SSS@MMMM\x015554\x04\xd4\xd4\xd4\xd0\x13SSS@MMMM\x015554\x04\xd4\xd4\xd4\xd0\x13SSS@MMMM\x015554\x04\xd4\xd4\xd4\xd0\x13SSS@MMMM\x015554\x04\xd4\xd4\xd4\xad\x0155\x03W\xa0+R\xb5z\x95\xa0*\xb5u\xa9Z\xbd\x01Z\x95\xab\xd4\r\x01Z\x95\xab\rM\x01U\xa9Z \xd4\xad\x00!\xab\xadY\xa9Z\x00kWZ\xb4\xd5\xa6\x80\n\xd5\xd6\xae\xb5u\xa0\x06\xb5+DGP\x8e\x80\x14\xd4#\xa2\xd4\r\x00)\xa9\xa2\xe3\xabc\xa0\x06\xb5U\xa2\xadJ\xd0\x03\xc7R\xb4I\xa9\xc7@\rjh\x88j\x1a\x00x\xea\x06\x8b\x8e\xa5h\x01\xe3\xa8h\x88\xea\xb4\x05V\xa7\x1d\x16\xa5h\x01\xadJ\xd1V\xa5h\x00\xadM\x1e\xa9\xd0\x03Z\x9a$\xd5V\x80\x1dM\x1dj\x93@V\xabGZ\x9ct\x00jV\x8e\xb5+@\x05j\xebEZ\xadhV\xa6\xae\xb5N\x80\x9a\xaa\xd5\xeah\n\xd4\xd5\xd6\xa6\xb0+SSS@MMMM\x015555\xa15554\x04\xd4\xd4\xd4\xd6\x84\xd4\xd4\xd4\xd0\x13SSR\xb4\x04\xd4\xd5\xd6\xaf@\rjj\xf5z\x00u554\xa15554\x04\xd4\xd4\xd4\xd0\x13SSS@MMMM\x015554\x04\xd4\xd4\xd4\xd0\x13SSS@MMMM\x015554\x04\xd4\xd4\xd4\xd0\x13SSS@MMMM\x015554\x04\xd4\xd4\xd4\xd0\x13SSS@MMMM\x01555z\x02\xb5u\xa9\xa9\xa0%jV\xafP4\x05j\xebUZ\xb7@MGVjh\n5z\xbe:\xb7\xf2h\x01\xd5\xd6\x885\x1d\x01U\xa8GD\xc7T?\xeb\xa0+\x8e\xa4c\xa3?\x8fMB?\xc2\xf4\x00\xc6?\x8e\xa2h\xf8\x1f\xe5\xa8\x8d\x9a\x00+RZ8\xed\xfe\x7f\x9e\xa3\x0f\xf4\xbf\xcfM\x00\x1c\x7fv\xa2\xe9\x8dv\xff\x00=I\x05\x7f\xaf\xef\xfb\xbe\xfch\x00\x81\xabv\xfb\xe8\xc8\xfa}\xff\x00N\x99\xd4\x8c\x7f\x0f\xbb\xf3\xf7c@\x02hM5;\x7f\xb5\xf6\xadS\x13\xd6\xfb\xfdz\xe3\xe5\xa0\x04??\xe7\xaa\xe3\xf9\xf9\x9atr\xf4\xc7G\xf7\xff\x00\xa6\xa9\x0b\xa3@)\xd4c\xa6\xbb]\xbe\x9d~~\x9e\x9a\x18C\xeb\xdb?\xc9\xd0\x01\xc3\xf7\xde\xa2t\xd5\xce?\xbb\xe5\xf9\xfezg\xdc=~\x7fM\x00\xae:\xba\xaf\xcf\xf2\xd5\x91N\xdd=>\xbf\x9e\xba\x90\xfd\xff\x00\xbf\xae\x80\n\xf9\xea\x07\xe7\xf3\xf4\xd3\x93\'o_\xcfMT\x9f\xdd\xda\xbf\x8f\x7f\xbf@-??\x9cj\xf8h\xa3U\xda\xff\x00~\xac\xdb\xcb\x8c|\xbf?\x87\xae\x80_\x1f\xf7\xd4\x96\x8b\xa7\xf9t\xbdX\xdf\xf2\xfc\xff\x00=\x00\xbd_\x1d3l\xbf\xe3_\xcfTC\xf3\xfeZ\x01|u\x18\xe9\xde\xef\xaf\xe3\x9e\xb5\xf9\xfa^\xae;#\xf9\xae\x9e\x99\xd6\xd8\x10j\x8d\xbf\xa6\x9em\x95\xf9\xf4\xf5\xd4\x95_\xa7K\xf4\xfc\xff\x00\x9e\x8b\x02\xbd\xde\xaf\x8e\xaf\x8f\xe7\xd0\xaf\xce~z\x8f\xe7\xf3\xe9\xf4\xd6\x80\xaf\xe7\xf3\xf9\xc6\xa9\xd1\xf1\xfc\xfd5}\xb4\x02\xd3\xf9jp\xd1\xca\x1f#\xd7U\x17@\x00j\x8d\x19\x1dD\xd0\x00\x9a\xad\x11\xaa\xad`\rjV\xae\xb5u\xa0\x055Z4\xd5V\x80\xa0\xd5&\x8bS@\x0e\xa6\xafT\x9a\xd0\xaa\xd4\xd5\xeah\n\xd4\xd4\xad_\x1d\x01Z\x9a\xba\xd5\xe8\x01\xadXj\xf54\x05j\xf5\x1dM\x0155+S@MMMM\x00:\x9a\x9a\x9aP\x9a\x9a\x9a\x9a\x02jjjh\t\xa9\xa9\xa9\xa0&\xa6\xa6\xa6\x80\x9a\x9a\x9a\x9a\x02jjjh\t\xa9\xa9\xa9\xa0&\xa6\xa6\xa6\x80\x9a\x9a\x9a\x9a\x02jjjh\t\xa9\xa9\xa9\xa0&\xa6\xa6\xa6\x80\x9a\x9a\x9a\x9a\x02jjjh\t\xa9\xa9\xa9Z\x02j\xebR\xf54\x05j\xf5+W\xa0%j\x1a\xbdA\xd0\x13Pua\xa9\xa0*\xb5z-_\x1d\x01Z\xb4\xd5\x9d\xff\x00\x87\xfb\xe8\xb8\xe2\xeb\xbf\xe7\xd3@/\xf2\xfezj\xd3\xeb\x9d\x14k\xa7\xe6\xb4eV\x80\x0fw\xa8B\xfbi\x84\x9a\xfc\x9d:\xba\xa6\rz\xdd?\xed\xfez\x00=\xdf\xd6\xbdk\xd3EY\xfaw?\xcb\xe9\xa2\xdc\x87c\xfd\xdf\xce4a\xd0\xacw\xff\x00_\xf2t\x028\xfag\xbf_M\x11.\xff\x00\xc3?\x9e\xda\xb77\xd3\xe7\xd4O\xf4\xff\x00MH\xed\xd9\x7f_\x9fO\xe05\xd6\xb4\x04e\xeb\xf8\xfe\x7f\x9e\xaa\x8e\xbe\x98\xc7\xd3\xf0\xd5\xa5\xf5\xfc{WwF\xc4z_V\xd0\xeb\xf4\xfd\xfa\x00\x08t\xf9\x1d\xbe\xfb\xba\xd5F\x16|\xce\xb6\xb7\xf9z\xe9\xbb1{\x8f\xcf\x19k\xb7|he\xd3\x91\xf8\x17\x8c\xfa\xfc\xb1\xa0\x05j\xc5\xfc\x0e\x9f\xc3\xe9\x87E-\xb0>Y\xf4\xe8\xb5\xf8\xff\x00\x1dQn^\xbd+\xf3\xf2\xed\xa6r\xa7\xb6L\xfdzS\x9e\x9f\x86\x80_\xbb\xfc=\\\x7f-Q\n\x93\xf2\xe9V\xff\x00\x0e\xbf\xbbE)\xf60\xe3\x15\xdd\xfc~_O\xc7N\xda\xdb\xbb;\x9fwO\xc8h\x04\xcf\xe8\xfc\xbe\xfc\xde\x8bso\xa2g\xe5\xfb\xeb\xeb\x9dFF[\xfa\x8d\xd9\xe9\x93\xd3\xd3D\xc1\xb1\xacV:G\xb5}1\xa0\x16P\xb7i\xf8\xfd~\xb5\xfeZ\x9c\xbaWw\xef\xac\xf6~_=\x14q\xd3\xe6a0\xd7\xafZL\xb8\xd1\x85/\xd3\x05}\xd5\xd4\xafZ\xc6\x80H\r\xe4\xc3}1\xe9\xf2Z\xc7]Y\x0e\xb5Npw\xfd\xca\x9adv2\xd8t>e\xfa\xbd\xbbz\xe8a\x0c\x15\xd5\xcf\xe1\xf9rg\xa6\x80\xa7r\xb1\xd8r%\xb5\xde\xf1\xf8j\xa5\x0fV\xa9\n\xe9\xfb\xbf\x1e\x9ad\x07\x00g\xbd_\xdf}i\xcd_GW\xb7\x1f\x97e\xf9\x89\xfc/\xb2\xe8\x00\x86\xdf_\xc7\xe9\x8e\xff\x00\x7f\xd3\xbe\x86OJ{~\xff\x00\x93\xfe\xba<=/\xa4k&-1\x7f,\xd7\xcbW)W\xf3=\x1f\x9d\xfd;z}\xda\x01{q\x1b^\xdd\x7f=?\x97\xe1\xab\x91o\xcf\xd7\xaf\xf0\xd3\x98\x16.G\x15\x8fKl\xc0WO\x9e\x97\xb5gO\xdf\xd2\xba\xf5\xfb\xb4\x02\xd8g\xa6=~\x9f?\xc7P\x8b\xda\x8fJ\xaf\xa9\xd7\xb7\xcfO\xf0\xc6Pin\xdb\xc3\xdf\xa5zb\xfaj\xe3\xb6\x17\x8c\xd7\\\xe2\xfdn\xba|\xd3\xe9\xa03Q\xf2;\xbf?\xdf\xf5\xc1\xab\x84S\xae1K^\x9d\xbbg\xe5\xa7\xc8,3nz\x9f\\?\x8fO\x97]P2\xc6N\xf6\xa5\x0b\x9f\xbcq\xe9\x97[`T\xa2\x7f>\x8b~\xb5\xd1\xc7\xa7\xcbE\x10~@w\xff\x00,}z\xe2\xf4\xe8\xed\xa7\x11\xa7\xaflt/8\xee\x97\xdf\x1dt\xa7f\xdf)\xf2\x03\xd4\xf5\xbb\xff\x00=hI\xc2\xfb\x95\xf2\xfb\xeb\xd3\xaf[\xc7\xdf\xa1\x8ci\xc9]s\xfb\xfe\x92\xfd\xd7\x8d<q}Z\xc8g\xb9\xf8b\xf1\xd8\xa6\xb1\xa5\xe7\xd0\xe8\x17nq\x8f\xc7\xbe{h\x05\xc9\xfaaJ\xfa\xff\x00\x1f]1\x9f\xcc\x7f\xe1\xc7\xf1\xeb\xf8z}*\xa1\x0c\x1d-\xc9\xdd~UM\xf7i\xe8j\xe7\x05>\xff\x00\xfe\x86\xe8\xce;\xfd?v\x80\x08\x18\xc6>\xbd+\xe7\xdb\x1f?\x97]\x03\x1fK\xf4{t\xed\xf5\xef\xa6Kk\xa9\xd8>e\x97Gk\xf9[\xfb\xf5Q\xfd\xe3}N\x8d\xfd\xcf\xe1\xd3\xe8h\x00\xab\xf5?\x9e\x7f\x8d\xe3T\xec\xe6\xbf\x8e{kV\xe4\n\xeczg\xa6R\xce\xbd+\xd37\xd7J\xabq\xd2\xba\xfd\xfd\xbd[\xeb\xf7\xe3@(\x83\xde\xbf\xcb\xf3\xd7C\xee\xf3\xf9\xfc\xf5\xf4\xd3\xe5X\xe8\x1di+\xa3^\x9e\x9f]W\xba\xbb\xf5\xcd_\xf3k7\xa0\x14G\xb7\xcb\xfd423\xf9\xfb\xff\x00\xdfL\x8d\xf5\xfb\xaf\xbf\xaf\xf2\xef\xaa%u\xdb\x1fw\xcf\xf2h\x05\x1f\xc3\xfd\xb5zc#?\x9c\xba\x1e\x1f\xcc\xd0\x02\x1a\xa9i\x95\xa1\xaf\xbf\xfd\xf5\xa0\x06\xabE\xc7\xe9\xaa\x97\xe7\xe9\xac\x015+EZ\x84t\x00\xeah\x8dS\xa0+\x8e\xa5j\xebU\xa0+SW\xa9Z\x02\xb5554\x04\xd4\xd4\xd4\xd0\x13SSSZ\x13SSS@MMMM\x00:\x9a\x9a\x9a@\x9a\x9a\x9a\x9a\x02jjjh\t\xa9\xa9\xa9\xa0&\xa6\xa6\xa6\x80\x9a\x9a\x9a\x9a\x02jjjh\t\xa9\xa9\xa9\xa0&\xa6\xa6\xa6\x80\x9a\x9a\x9a\x9a\x02jjjh\t\xa9\xa9\xa9\xa0&\xa6\xa6\xa6\x80\x9a\x9a\x9a\x9a\x02jV\xa5jh\x0b\xd5j\xebS@CWZ\x9a\xb3@V\xac\xd5\xd6\xac4\x05D\xd5\x86\xac\xd5\xc67\xa0(\xd4\x8c\x7f\xcbD\x9a\xb1_\xe5\xf5\xfd\xda\x00kG\x13\xf1\xfc\xd6\x89\xdb\xfc\x7fw\xdcz|\xf5rpg\xf0\xff\x007@\x07\x1f\xdd\xf9\xe8\xe8\x88\x9d\xbb|\xaf\xbf\xe1\xab\x97{\xeb\xd9\xff\x00?\xf4\xd5\xc2\'^\xb5\xe9\xd8\xee\xb8\xd0\x01\x08\xdf\xf9\xf4\xfa\x1e\x8e\xa6\xcc;g\xb7\xfa\xfe\x19\xce\x9a\x87A\xbao\xbfN\xf5_\xef\xab\xce\x1c\xa5\xb6\xbd3\xd3\x0e2wt\x05p\xeby/\xa9\x9e\x9e\x9f"\xfd4K\x83=.\xab\xab\xd0\xc6:\x7f\x96\xa4g^\x89TV:\x97\xde\xfb\xf6\xbbuq\x83\xd7\xb6+\x18;\xb8\xc7\xf9u\xd0\x01\xb65m\xd7f\xb1\xf4o\xf8\x99\xd4\xe2]\x14\xb5\x94{\xf5\xcd\xd6\x8boj\xdc!o\x1e\'\xcf\xbetS\xf0\xafa\xbc\x9fq\xd1\x1czv\xd0\x03\x1d\xa5:r~\x7f^\xdf/\x96;\xea\xf8\xbd\xbat\xea\xd7\xdd\x8c~!\xf3\xd3\'\x0c\x94\x92\xbc\xe4~W\xdb\xaf\xdd\xf8\xe3EAw\x8b+\xab\xd7\xfc-w\xeb\x8f\xbf@g\x9e\xddzu\xa0\xebc\x9a\xf5=n\x8d\x14^?5#\x9f\xdf\x87\xe9\x8a\xcf\xdf\xaa\xde\x8du\x1e]\x9eV\x01\xe9\xea\xdf\xaflV\x99\xb1\xe1\xdfF\xfb\x7f\x9e\x7f\x81\xa0\x03\xdev\x01\xbb\t8k\xd1\xaa\xfd\xdf\xcfL\x8c\x12\xab\xcau\xab\xbb\xaf\xbb\xa9\xe9\xe9\xa0\xde\xd9h\xf4\x13\x17\x9f\xbe+Aw\xd9\xe9\xd3DJ\x81\xa2\xae\xc0Z\xef\x1cU\x95ym\xd0\x00\xd2f\xdc\xfd\x0f\x98\xd1\x84{|\xcfM\x11\xb3\x17 \x1dN\xb6\xdd\xf5\xec\xfd?\x9e\x86R\xe9Qq\x96\xf2u\xce\x1cg\xb5\x19\xbdH\xe3\xd0\xc7\xc4\r\xe3\xbfK\xac\xd3\xd7\xf8h\t\x1d\xa3/\xe0?\x86G\xa7\xad\xde\x82-8\x00\xc3\xeboJ;|\xf3\xf8\xe9\xde\xf8\xa77\xf0\x98> m\xf4j\xbd[\xd0\x9b|yUP\x0f\xab\x9a\xf4z\xdfg@\x1b*\xca\xb6\x8fdW?X\x9f*\xec\xe9l\xe4\x87R\xee\xd5\x1ct+\xbf\xaf^\xfd4\xed\x9f\x11\xe5\xe8F\x9e\xb5K}:c\xe8t\xc7\xe37\xb6\xaf\xb5\xd7\xd1Z\xbc\xfd}j\x83\xe7N\x80\xcb\xb2\x1d*\x9e\xdfU\xf5\xfau\x1b{h\xf7#\xf0\xf5\xcd\x8e>mU\x0b\xf7u\xd1n\xee\xd5\x11\xea]\xfa\xf5L\x0e,\xe9\xfc\x1d\x1b\xb7d[\xa1\xccm#h\xfa\x97V\x7f\xdd\xfd\xda\x01\x029\xac\x19"Y\xd3\xd7\x15\xdb\xe4\xe3P\x87j\xac\n\x9e\x99\xbf\xdf\xd7\xe7\xad\x1b]K\x13\xb1,&:\x16\xe1\xd5On\xce\xa1GV\xf0\x8a\xa6>\xd7z/@\x0f\x1e\x9cl\xc0\x83g\x10\xea\x18T\xb6\xcc\xean\xeeSg\xda\xa7\x05\x1dz=\xef\xaf\xcf\xf93mX\xb5\x85\xea>\x98\xf4\xb5\x1b\xbc\x87^\xfa^\xcc\xf2\xe5hr\xf6-\xacf\xcf\xbb\x17z\x00e\xb7*98{6\x8at\xfa^;\xfa|\xf4[\xb0*\xa2[\xd6\xc5{\xd3\x87\xa9\xd0?6R\x81\xc5\xbe6H1\x16\xdb:\xdfW\xf7}\x1d\x16\xee\xcb\x977\xd4~Fo\xaau:K\xe7\xad\n\xf0\xc0U\xdf\x9a\xf0V;\xd7\\8\xaa\xc3\xf5\xd2\xcd\xcb\xba\xc56t\xc9T\x92\x07\x1d}\x1a\xb7\xa5kG\x8a\xd9E\x97\xc1\xdb\xb6l\x95\xb7\x92\xdc\xe3=\xbd4\x91\x92\x1d\x18\x9e\x85X\xf4\xbaN\xef\xd3@\x1f\x87\x84[\xf4S\xa6*\xa9\xae\xd83o\xa6kS\x9f\'\xbdU\x96Z\xd5\xbe\xa7^\x9f\x97O%\xea1\x96\x15\xea\xa7S\xab\xc7\xb0\xe7\x06\x95\x19\xf9\xbb\x1cD\xa0\x89\x84\xbb\xabm\xee\xe5?\x86\xb4\x03s\xb0\x1dR\xecpWH\x9e\xb5\x96\x9a\xf4\xd0xx=\x19t\xed\xdb\xaci\xa2\xaf\xb5\xf5\xc7\xd3N\x8d[\xd0\x1b\xbb.Tc\xee\xb5\xbb\x02\xb0j-6Y\xc8Z\x0b\x11C\x8fS\xa3\x86\x97\xe4\x18\xd0\x0bE\xae\x8fn\xbe[\xe9\xc9\xa3\xccXz\x9fN\xcd\x86\xdf\x19]\xe2G\xd9\xba\xc9\x9e10\xdaP\xe8w<\x1f\x9a#U\xd3\xcb\x99|\xaf\xcd]\x93\x97\xcbG=\xb3\x9a\xb7\x91Jy\x15\xd1\xcf\xa5\x0b\x80\xaf\xc3@M\xebb\xb7t\x92\xa8\xdb\x86\xacV\x9b\x0e\xbdh>z\xcf\x1b\xc5\x06F\x836XW~\x9e\xaf\xf9i\x9b\xb0~\x18\xd9\x1a\xa0\xccl\xab\xec\xa4\xaf=K\xf5\xad,\xd8{8\xf8\xb0\x8dPg\xa0\xe2\xb2\xd6:\x9do@^\xe2\xd1\xf4:]\xdei.\xba\x94]w\xee\xe8c\xb9wCQ\xf8\xab\xd2\xb3\x99\x0f\xef\xf9\xfd\xe7\xfdad\xf4E\t8\xa5\x04\xfa\x03\xd4\xce>z-\x998\xbb\xa6\xf8\xf1m\xac\xc5R\x9b\xe9E\xd64\x05>#>nC\xeb@\xf1\xe9E7\xf7\xf4\xfek\xda\xf0\xe2\xb6\xaf\x97\x95\xbdq\xdb\xaf_\xc4\xc7\xce\xf4\xef\x11\x0c\xc4\xee\t\xf4\x88\xd0\xd7g\xa6yv\xfcdv\xaf\x14+\x1b\x8bk\xe5\xba\xf3%"\xd2_\xf04\x02\x89d\xf9\xb9\xc7\xc2\xc9\xbf\xe5f{v\xd4\x94\x17\x8d\x15\x95\xfaW\xc9o(\xae{\xe8\x88\xc8\xeb\xda8>Yl\xcd\xa9\xd3\xbe/L\xd9\xd8[d\xe7\x01]jN\x19|\xb3akGJ\xbd\x01\x9f\x86:\xe25t^m\xf5\xf9\xff\x00\x97mM\xd4\xe8\xe2\xcbW9\xf9c8\xed\xa2i\xcd\xf5\xb0\xae\x98\xed\x9c]7\xf2\xb6\xaf\xb1\x1b=\x8a:\xda\x8d\xf6}\x04z\x15\xdf=1\xa03\xeem\x95}[\xa7\x19\xa2\xfb|\xf1\xd8\xae\x9a\xae\x14z]c\xe5\xfc\xae\xef\xaf\xdf\xa6\xf1\xbb\xae\xed f\xab\xa9\x9c\x16=uu`\x16\x85\xf4G8hz\x0f|zh\x04\xeen\x03Y\x7fy\xd3\xd7\xbe~^\xbe\xba\xafw\x86\x9f\xf3\xef\xa7\xc2\x07C9\xf9t\xe9\xdf\xa7\x9b\xe9\x8dS\xb1\xe9\xe8\xdd\xb7_\xce\xd3\xd3\xe5\xad\x0c\xc9\xfe\xdd\xebP\xaf\xa6?7\xa7\xbd\xfa\xa7\xcb\xeb\xd2\xff\x00\x90\xff\x00\x1d\x0f\x1f\xe1\x7f[\xfc]\x00\x92\x1f\x9f\x96\xa9\xfc4\xc2\x1f?\x93\xf9\xe9Z\x19G\xf7w\xf5\xf9\xe8\x01uI\xa2\rN:\x00\rRh\xafQ4\x00jV\xad5+@V\xa6\xa6\xa6\x80\xadV\x89\xd5V\x80\xadMMM\x015554\x04\xd4\xd4\xd4\xd0\x13SSS@\x0e\xa6\xa6\xa6\x90&\xa6\xa6\xa6\x80\x9a\x9a\x9a\x9a\x02jjjh\t\xa9\xa9\xa9\xa0&\xa6\xa6\xa6\x80\x9a\x9a\x9a\x9a\x02jjjh\t\xa9\xa9\xa9\xa0&\xa6\xa6\xa6\x80\x9a\x9a\x9a\x9a\x02jjjh\t\xa9\xa9\xa9\xa0&\xa6\xafU\xa0/SR\xb5n\x80\x9a\x8e\xafS@CWZ\xb0\xd44\x05\xc7V\xcbRQ\xd1\x90\xf9\xe8\x01\x8c{\x7f-\x13\x1c\xd7\xd3\xe5\xaa!O\xcf\xe5\xf3\xd1\xbbxs}??,|\x8d\x002\x1c\xd7\xe7\xbe\x8a2\xf9\xfe7\xfe\xdf\xed\xa36\xeb\xff\x00\xa1\xe9y\xc3\xf4\xfeY\xd0\xc6>\x87N\xbfG\xef\xa7\xbe\x80\x86\xdfJ??\x9e\xda=\xdf@\xc3\xdd+\'\xef\xf4\xd1\x11\xf9Z\x14\xe7\xbd\x95\xdf\xd7\xeb\xfeU\x0c-\xf4\x13\xd7\x17\xf7_\xafO\xbf@S\x07\xebe\x89\xdb\xf3\xea\x9a-\xbf\x0c\xdfE3\xcb?\x8d\xa5\x0es\xfez=\xe8|\xae\xa9\xae\x98>X\x97\xdd\xf5t[Fp|_qx\xc7\\E\xe9}]\x01U\x17\xb7dS\xd2\xbf\x81\x8e\xddM.pb|\xf3\x9a\x11:c\x1e\x97\xd6\xbf\x9e\x99\x1d\xa27\xd1\xf4\xb6\xe9\xf9v\xbb\xe9\x8e\xfa)m\xd7!\xb0\xc0\x05\xbf>\xe6\x1cv\xac\xf6\xf4\x00a\x00\nl/8\xca]z\xe37}{zh\xb6`w\x95\x1f3\xb0t\xab/\xf0\xbf\x9e\xaaH\xe4yI\xec\xc53u\xd9\x1b\xef\x95\xd0\x90\ni\xae\xbd\xad\xce.\xad\xbb\xd0\x0c\xe2v\xa0LW\x99\xf9\x8d\xb7\x96\xd3&\xaboy\x0c\x00K6Z\xf6\xb6\xbdms\xa0\xd8\x8d\xe6\x9b\xc8\xf4L\x9f\\c\xab]\xbez(\xed\x9d0\xf5/\xedzXt\xc7Q+@I@%\xdc:\xf40\x9d\xae\xfeE\xf5t[\x8bCH\x96\xf1z|\xde\xb6~>\x9dt.\xc5B\xfc\xb7\xcb\xa6:w\xefw\x8e\xd9\xcf_I\x1c\xd8EK{\xb4w\xc7\xdf\xfex\xbd\x00S\x97B.B\xd6\xdf\xe3]\x0e\xa3\xde\xbez\x129\xeb\xe5S\xa0S]1~\x97\xf2\xef\x9dW\x15\t\x07LQ\xd2\xbd2\xf2mB\x9e\xdd\xf4\xc8\xef\x87Pp\xdck\x03\x8a\xb34\x9f\rg\xf7h\x01a\xe5\x8d4]rO\xe7\xe9g\xf9\xe8}\xed\x063\x9a>+\xefo\xa7\xadf\xafL\x8e\xd6\x07\xb7[rt\xba\xae\x99z8\xce\x95\x87\xb1mW\xa9\x9c\x07\x99\xf9v\xf5\xf4\xd0\x15\xbb\xb3e\x95t8\xa6]+\xb2c=R\xf4\xd8l\xd5u\x0b\xaaEq\x92]\x1f\xdfE}\xfa\t2f\xd4\x8c\tc\x8c\x1d\x07\xaf\xdf\xd3\x1f-7qh-\xaa\xc7\x16\xee\xf1\xd6\xab\xaf\xc8\xc1\xdf@W\xf5\x82\xfc\xa2\xe7\r\x98S\xb0\xde\x1a\xf4*\xa8zip\xdb\x12U\x86\x87\xe2\xb9]\xf4.\x9f\x9fn\x9f=;cc\xa53\xf9\xf1\x04X\xca\xb1\x9c\x87k\xf4z\xe7K\xdf\x1f\xa3}eY\xb6\xa5u\xd8z\xe3\xbfm\x016\xbe\x10\xec\xe5\xabn\x959u\xcd\xf7;.4Q\x9b\x93\xa5#\x95X\xfd\xde\x8d\xd0a\xbf\xc7N|9O[\xaa*\xab\x14"\xdeE\xcd\xd2\xe2\xfah\xbcK+\x19c\xa1\x12\x8a\x961\xd3\x17\x7f:\xa35Z\x01\x06\xcf(\x93nOW\xd6\x87\x0ep\xf5\xec\xe8\xe7\xb4\xc9\x8d\xc3\x89\x8a>\x8dR\xb5\xd6O\xc5\x7fh\xef\xaa\xdc\xa2?\xf1\x18o\x89\x19E\xbeE\xf4\xa3\xa1X1\xdfR\x05#\xc9J\xac\xca\xfc\xa1\x98\xddPW\x9b\xa2t\xf4\xb7B\x86\xdc\xf9s\xd2\xb3`b\xf2u:\xb9ru\xd4\x97\x87\xe3O+Q\xe8_jL\xb9k\xa3\xf3\xfaj\x02\x80\xca^T\x90]\x96\xfa\xa7D\xafK\xcd\xe3Q\xcc\xa3g\'\xad\xb9\xe9w\x8e\xbf1\xbc`M\x00[~%\xb5\xe8c\xbb\xff\x00\x16n\xac\xab\xba\xcfl\x98\xd0\xcf\x8b\xf0\xd8Z\xd3R\xba\xf8\xa9\xeb\xf3:\xb5\xd6\xb1\xa7Gi\xbf\x95\xd0\xe75\xdd\x93\x87\xe2\xe8\x17\x85~s\xc5\xbc\x90\xb8\xb8qQ\x06\xec\xfb-\xe6\xbbzv\xd0\x0384P\xb2l\x1c\x8e\x0c\xa0\xf5\x1e\x83vg\xd7\x01\xbf\xc2%G\xcdv4\xb2\xb3\xaeP\xaa\xb37n\x0fV\xae7\x8c\x81\x15\xa0\x93\x84|\xd5e\x97\xea^\x8fr|zW!\x16M\xe7\xbb\x88\x9f\xea\x97x\xd6\x82%+\xc2\xdfT\x89\x1b\n:\xe2\xba\xf4k\xa7\xde\xbaf\xdd\x05\xc7\xbe\x17\xac\xb3\x8a\x95g.\x02\xe8j\xf4>\x13q.\xa3$n\x81\xb7>oJ\xfb/o\xb9\xce\x8aB\x8c\x83\x8cyvV\xb8\xfcVf\xde\x9dk\xd4\xe9\xa0+nF\x10$\xd1@\xff\x00\x8b\xb2=\xa9\xbbGM\x96\xce\x1e1*6\xb7\xc5\x91Nm\xaa:b\x8f_SC\xeeS\x02\x88\x9co\x8eK\xc8\xcb\xe2(\xb7\'l\xbd\xb4\xcd\xed\xa0\x1c\xc9\xb9w_\xb5\x85qI\xcb\xd2\xa9\xaf]\x00\xb8\x0c\x99K\xcb \xb9q\xc7[h\xc7p-#\xd8\rV\xdc\x1f\x8f\xbdP\x0cQV\x84\xc4\xab\xd5\xa8\xd7^\x99\xd36w8,x\xa7\x1f-\xc4\x19JD^\x8dUa\xbcd\xbd\x0b\x18\xd5\x8dK\xe1\x8ej-b\xe2\x1d3\xd1Z\xb6\xfb\xe8\x04Gs\t\x01\xae\xa7R\xdc\xe2\xaf\xe6\xd3\x17\xe5Z\x91\xc4\x94\xaa\xbc\xca\xd0\x93W_N\xadf\xcdh\xd8~N\x02Dh\x95QB\xd2\xc81e <Z\xce\x80|\xd7\xd4ZE\xeb+\xafDZ\xac\x86mqi\xa0/n\x11U\xcb\x9cSVY\x98\xbe\x81u\x11zw\xeb\xa5\xf8\xa3#\x1c\xd5\xc6\xf2\tx;b\xaf>\x9d\xf1zl|;~n*b\\\x8e\x99\xcaW[\x97F\xae\x9f\x9e\x0cp\x95\x18\x95Rm\xa3\xd4\xc0\xd0t\xce\x11\xb2\xebZ\n\xf0\xdb9\x1a\xc3X\xb7\x89q\xc4m\xc5\x17\xdd\xbb\xfb\xb4\x13\xde\xb96\\\\\xd2\xc4\xcccTQhI)\x8f\xd7\xd7O\xda\xf0\xb9"\xf1\x9d\xe3\xcd.83\xe5\xcf\xa2\xf5;^+9\xf6\xe1\x17\xec\xbek\xe3*\xc3\\\xc6\xad\xf2\xa1\xf3\xed\xf4\xd6\x03=\xd2\xa6>O&\xf1\x1aH\xf6\xc2G\xa2]\xe7L\x8f\x97\x14G\xaf\x1eIf9\x0c\xba\x88ur\xb9\r\'og\x8d\xd9\xd52H\x92I\xe3\xd6\xda\xceW\xe8\x97\x9cV\xc6\xccS>j\x8d\xf1\xba.\xe5m\x97\xcb\x8d\xd6)^\xc8\xe7A{{\xadJ\xbe\xd0\x15\xfb\xda\x7f\x86j\xb3\xa1"\xc9\xa2\xed\xc9\xc8\x06\xba\xd9W]\x1c\xf7\xfc\r?cj\xf1\x8b\xc1\xd0\xe2\xbd\xaa\xcf\x85\x8b\x8a\xef\xcb\xb5j\xd9\x88Sy|\xd8e\x03\x15Q\xeez\xf1\xaf\xe2h\x05@n\x9b\x0c_\x94\xf5b\x95\xd3\xe4H\xf4\xbd3\xdd\x1d\x00\xb1\xa4\x1aP[:\x97\x8e\xfdq\xda\xf1d\x95\xa8\x99\x0e\xc0\xb2Yq\xfb]\n\xed\x84^\xc6\x8er\x88\x02\xb6\x05^m\xf2\xb2G\xd0\n\xa7\xd3\xeb\xa0\x158G\xe2\xefw\xe9}<\xbe\x97\x1bo\xf1\xc5\x94\xb6."R\xe7\xa7{\xebON\xb6_\xd3\xe7\xa6x\x9f\x0f\x998\xb35\xff\x00\r^k\x17\x1c\x02Qc\xf4\xd0m\xcb\xca\xb1\xf9D\xacZ\xe5\xbc\xb5\xe9G[\xfa\x00\t\xdc\x07\x06d8\xa6\xf0*\xf5\xbct\xaf\xe7\xaa\xdam\x93Y\xea]\x15\xd7\xee\xc5\x95\x8e\xb5\xf3\xd3\x1b\xcd\x17V\x07\xa1U\x90+\x1f\xbb\xaeqRgG\xe6\xd3U\x9e\xf6\xfa\xd7\xae/@T\xf6\xfbUa3\xfe+\xbe\x9f\x9f\xbbJ\x84(\xc1\xd2\xef\xb7\xc8\xae\xb9\xf9i\xf2\xc9\xcb\xbdu\xe4\xfd\xf9\xae\xbf\x9f]\x06\xe4N\xb5]\x02\xfd}z\xfa~\xff\x00\xbfZ\n\x94\xf0\xfc\xff\x00v>\x9fv5U\xf5\xfa\x7f\xaf\xcbL\xdci\x7f\x8f\xdf\xfb\xbb\xe7UO|u\xfb\xab\xf9\xfc\xf5\x80\xb4\xa3\xe9\xfc]T\xa3\xf9?\xcbV\xc6\xbdz\x1f\x8d\xd6\x8d;\x87\xcd\x7f\xd0\xf4\xef\xad\x04\xea\x97DG\xfc\xb4$\x7f\xc9\xfc\xf7\xd0\x02\xea\xb4L?\x1dD\xff\x00M\x00\x1a\x9a\xbdUh\xb0D\xd5j\xf5Z\xcb\x05:\xad[\xaa\xd0\x13SWZ\x95\xa0+WZ\xbdM\x01U\xaa\xd1^\xaf@+SSSH\x13SSS@MMMM\x015554\x04\xd4\xd4\xd4\xd0\x13SSS@MMMM\x015554\x04\xd4\xd4\xd4\xd0\x13SSS@MMMM\x015554\x04\xd5\xeaj\xb4\x05\xea\x1a\xba\xd4\xd0\x12\xb4A\xa1\xad\x1dh\n\r]j\xcdC@H\x9a8\x8f\xe7\xf9\xea\xb9\x7f\x9e\x99\xb7\xeb\xf8\xe8\x01\x8f\xd0\xcfm\x10\x15\xf9\xbe\xbf\xbfP\x0b\xc5\x1e\x9f7\x1a\x93\xdb\xef\x9az\xff\x00\r\x00F\xdfs\xef\xcf\xe1\xf9\xadT^\x81gw\xf3\xf9\xe9\xa2e]k=\x038={h\x8b\x1e\x9d*\xce\xd4\xfd\xedv\xfb\xf4\x04\x94\x0b\xcfW\xadu\xae\xde\xba=\xbd\xbfN\x97\xd5\xf4\xbe\x94+\xf9\xf9\xeaJ\\i\x17\x8b\xeb\xd5q}\xba}z\xe7EO\xc5\x87\x1d\xcc=.U\xdf\xea|\xbe\xba\x02n\xed\xb4\xd3\xd2\xf1\xd6\xbb\xf5\xfa[\x7f\xe9\xa8\xd7\x9a\xdb\x1e\x9f^\xfd\xed\xc8\x18\xe8g\xe5\xa5Ku(0Uf=\xf0\xfd~\xfdh\x91\xc7\xb3Y\xcauR\xff\x00\x0c\x15\xd3\xa7}\x00\x925,a}{=\xca\xe9gS\xee\xfb\xce;yo\xadYT\x92-3\xd2\x8f\xc3\xa1\xa9\xb91x\x9d\xc8\xe5G=2\xf4\xae\xdd\x9c_m\x14\n|\xc7\xa3_sB\x91}t\x01xm\xbe)\x9b3\xc4\x8d\xd7\xe3]{uj\xfa\xf7\xd0{\xa4\xe9w\x96]2\xfc\xb3\x93\xf8\xfc\xefE\x19t\xe3\x86\xda;\xc7\x19\xa7\xa7^\x8b\x9c\xfaj\xb76\x81V\xd0>\xd5\xdf.\x99c\x8f\xbf:\x02\xb8\x85[\xdcd\x17Lz%`\xbf\xe5\xdfD\xc2\xec-n\xee\xcb\xe2|=i\x8e\x1az\xfa}K~\x1f\r\xc7\xd1\xc6"\x96\x16\xbd;z#zB\xd2[bu\x8fN\xbe\x88]\x15wZ\x01\x9e"-\xb7W\\\xab(b\xbe\x95\xde\xce\xfa\xb8DG\x95\xf4\xact\xc3V6\x0b\x8a\xa1\xff\x00-.\xf3\xce\xfd\x12\xb1\xcb\xbfK\xc3}W\xf0\xd4\xdd\x99]=^/A\xff\x00\x87\x8b\x86\xd7\xee\xad\x00S\x95\x95\xc4\x8ehn\xd7\xa3Y@\xaf\x9f]6\x11\x18\xb9z\xf1\xf2\xf5@\xeev\xbf\xab\xd2\xb1\xaa\xe1\xd2\x8a|\xae"\xf1\xc1\xd1\xb6\xf1\xd1W\xd7VA\xae\xaf)\\\xa3\xc4\xbc\x8a\xd6\x0e\xaf_D\xad\x00\x89e\x0c\xe3\xf1_\xf1Xz\x07^\x9a8\xb5uS\xefm\xf4\xb7\xab\xd1\xcb\xa3i\tF\x83\x17@%^>y\xb7\xbe+\xeen\xf6\xc5\x91\xba\x15\xbe\x98\xbf\x8b\xcaV9\x15\x8a\x0c\x9do@e\x8c\x93\xabUTU\xdbu\xd3\xaf\xce\xfa\xd7cG\r\xce\xdd\x12\xba)\xe6\xea\xca\xab5\xd7\xf7i\xbb\xc6=\x03\x05\x86$\xfd{\xfa\xad~\xed\x1e\xe6\xdf\x91\xf8N\x9eiE\x1e%\x1dmk\xaf\xafd\xadhg7\x1e1\xa1\xa5i\xf5\xeb\xd9<\xbd\xb2&\x17L\x84\x90ho*\x8eo4\xf5\xaan\x9e\xbd59p\xf36\xddZ\x98\x14\xf5\xebe\xddWn\xbdm\xf2\n\xb8\x96\x17\x97\xcb\x9e\xbe\xb6\xf5^U\xf3\xfa\x00\x9fyCu}\xa3\x81\xefM\x0fP\xbf-\x1d\x9b3\xaa\xdc\x04\x07\xd2\xa4\xa7\x1b\x07\x14w}n\xf3\xa6\x99x\x98jV\x00\x9c\xbdK\xb53y\xe8\x1d\\\xba\xad\x9f\x0e)*P\xcf*2\xb7Q\xe3iW\xda\xba\xe8\x01\xd9[\x8d\x17d\xb8\x9d\xc1_2\x84YY\xe9\xf2;\xe8\xb7\xbc^$G\x05\xff\x00\xddK\xe3M%\x98\xbf\xb9\xeaj\x1b\xef*x\x84l(.\x87$\xba\xd0-\xe6\x93K\xf7\x03,9G1lz\xfa\xe1\xe9\xd5\xa76t\xd0\x04\xaa\xd7\x13\xbcU\x96)\x0e\xb6\x1d\\\xd7[\xc1Z\x03k\x07\x99\xe9Uo\xcc\xb4\xbb\xa291\xf6\xba\xe9\xe6!\x11\xf31\x985,\xb8\xc5\xd59\xa6\x9eX\xae\xda\xb3q\x94\xa9>\xd7\x0eJTC%\x1cn\xff\x00\x8fO\x9e\x80L\x96rh\xbe\xad%\xd3T\xc6\x89U8\x17\xad\xbd

In [21]:
with open("data/dotcsv.jpg", 'wb') as f:
    f.write(image.content)

### Mediante pandas

In [ ]:
df_inflation = pd.read_csv('https://datahub.io/core/inflation/r/inflation-gdp.csv')
df_inflation.head()

  Country Country Code  Year  Inflation
0   Aruba          ABW  1985   4.032258
1   Aruba          ABW  1986   1.073966
2   Aruba          ABW  1987   3.643045
3   Aruba          ABW  1988   3.121868
4   Aruba          ABW  1989   3.991628

In [23]:
df_inflation[df_inflation['Country'] == "Spain"]

     Country Country Code  Year  Inflation
2904   Spain          ESP  1960   1.177771
2905   Spain          ESP  1961   0.809253
2906   Spain          ESP  1962   5.706477
2907   Spain          ESP  1963   8.743698
2908   Spain          ESP  1964   6.979247
...      ...          ...   ...        ...
2964   Spain          ESP  2020  -0.322753
2965   Spain          ESP  2021   3.093135
2966   Spain          ESP  2022   8.390576
2967   Spain          ESP  2023   3.532361
2968   Spain          ESP  2024   2.774178

[65 rows x 4 columns]

## Bajar datos de Bicimad

In [34]:
url = 'https://opendata.emtmadrid.es/getattachment/c3383795-121b-4ebf-98b4-c7b05e902eaf/202106_movements.aspx'

r = requests.get(url)

In [35]:
r

In [36]:
# Guardamos el zip
filename = 'data/bicis.zip'
with open(filename, 'wb') as f:
   f.write(r.content)

In [37]:
# Extraemos lo que hay dentro
filename = 'data/bicis.zip'
with zipfile.ZipFile(filename, 'r') as zip_ref:
    zip_ref.extractall("data/")

In [38]:
# Leemos los datos
datos_bicis = pd.read_json('data/202106_movements.json', lines=True, encoding='latin-1', nrows=10000)

In [39]:
# Vemos qué pinta tienen
datos_bicis.head()

,_id,user_day_code,idplug_base,user_type,idunplug_base,travel_time,idunplug_station,ageRange,idplug_station,unplug_hourTime,zip_code
0,{'$oid': '60bbf3f21b91311d90d568ad'},b67ea824acf706087d5818ebc6f90821a5abaab17a0868...,15,1,13,319,38,0,54,2021-06-01T00:00:00Z,
1,{'$oid': '60bbf3f21b91311d90d568b2'},364b1b99f1f9a1748f7abf1134c8d6a46197b583649308...,7,1,1,386,185,0,126,2021-06-01T00:00:00Z,
2,{'$oid': '60bbf3f21b91311d90d568b3'},5cc17031cba02835dda4b6c153b56572beaade54d8ab91...,14,1,10,465,15,0,91,2021-06-01T00:00:00Z,
3,{'$oid': '60bbf3f21b91311d90d568b4'},6e855acaaa17d6d14236598c0f1172c783e16950e39c01...,8,1,22,613,84,0,236,2021-06-01T00:00:00Z,
4,{'$oid': '60bbf3f21b91311d90d568b5'},e93417502d55208995a61f4177956ab9289aba39044ce3...,1,1,4,751,131,5,94,2021-06-01T00:00:00Z,28006

In [40]:
datos_bicis.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   _id               10000 non-null  object
 1   user_day_code     10000 non-null  object
 2   idplug_base       10000 non-null  int64
 3   user_type         10000 non-null  int64
 4   idunplug_base     10000 non-null  int64
 5   travel_time       10000 non-null  int64
 6   idunplug_station  10000 non-null  int64
 7   ageRange          10000 non-null  int64
 8   idplug_station    10000 non-null  int64
 9   unplug_hourTime   10000 non-null  object
 10  zip_code          10000 non-null  object
dtypes: int64(7), object(4)
memory usage: 859.5+ KB

In [41]:
datos_bicis['zip_code'].unique()

array(['', '28006', '28004', '28045', '28028', '28009', '28007', '28005',
       '28010', '28034', '28012', '28001', '28008', '28015', '28002',
       '28105', 'CODIGO_POSTAL_NOT_DEF', '28013', '39724', '28100',
       '28800', '28027', '28020', '28011', '28014', '28850', '15002',
       '28003', '45007', '28046', '28039', '28043', '28038', '28934',
       '28016', '28945', '28221', '28033', '28030', '28029', '28048',
       '28054', '28035', '35572', '28049', '28004 ', '28019', '28040',
       '28941', '28523', '28380', '28933', '28026', '45600', '28938',
       '28220', '28935', '28760', '28863', '28018', '28250', '28053',
       '28017', '28024', '28823', '28021', '28922', '28210', '28022',
       '28036', '28047', '28430', '28041', '46009', '28770', '28031',
       '28200', '46026', '20540', '28232', '28042', '28071', '18006',
       '28400', '62973', '2', '28521', '28822', '28411', '28229', '48520',
       '29039', '28260', '28055', '28942', '28815', '28037', '28702',
       '28707', '28701', '28290', '28691', '28460', '28936', '28915',
       '28025', '28750', '28905', '28223', '75014', '28891', '28903',
       '23009', '28023', '28660', '28006 ', '28924', '28911', '28032',
       '28801', '10318', '28803', '29740', '28051', '28342', '28912',
       '28064', '28299', '33206', '28791', '28028 ', '09006', '28917',
       '19160', '28923', '28350', '29045', '23012', '28670', '28044',
       '28909', '28450', '28906', '28231'], dtype=object)

# Acceso a archivos de la pagina de datos.gob.es
Uno de los mayores catálogos de información pública descargable en España

<table align="left">
 <tr><td width="80"><img src="./img/ejercicio.png" style="width:auto;height:auto"></td>
     <td style="text-align:left">
         <h3>Ejercicio datos.gob.es</h3>

Descarga con pandas un dataset de la página https://datos.gob.es/es/catalogo acerca del empleo y guárdalo en un csv en la carpeta data. Puedes utilizar pandas.
         
 </td></tr>
</table>

## Api chucknorris

[Enlace API](https://api.chucknorris.io/)

In [35]:
url = "https://api.chucknorris.io/jokes/random"  # Reemplaza con la URL de la API que deseas acceder.

response = requests.get(url)

if response.status_code == 200:  # Código 200 indica una respuesta exitosa.
    data = response.json()  # Analizar la respuesta JSON.
    print(data["value"])
else:
    print("Error en la solicitud: ", response.status_code)

When Chuck Norris was 8, he acted out in class and was told to go to the Principals Office for a spanking, so Chuck went to the Office and gave the Principal a spanking.

In [37]:
def get_joke(url):
    response = requests.get(url)

    if response.status_code == 200:  # Código 200 indica una respuesta exitosa.
        data = response.json()  # Analizar la respuesta JSON.
        return data
    else:
        print("Error en la solicitud: ", response.status_code)

In [42]:
url = "https://api.chucknorris.io/jokes/random"
get_joke(url)

{'categories': [],
 'created_at': '2020-01-05 13:42:23.240175',
 'icon_url': 'https://api.chucknorris.io/img/avatar/chuck-norris.png',
 'id': 'bPLrJsWcQQK3LAavXOmVlw',
 'updated_at': '2020-01-05 13:42:23.240175',
 'url': 'https://api.chucknorris.io/jokes/bPLrJsWcQQK3LAavXOmVlw',
 'value': 'Chuck Norris made the mayans extinct.'}

In [40]:
url = "https://api.chucknorris.io/jokes/random?category=food"
get_joke(url)

{'categories': ['food'],
 'created_at': '2020-01-05 13:42:18.823766',
 'icon_url': 'https://api.chucknorris.io/img/avatar/chuck-norris.png',
 'id': 'fw_gwlvrsl-7fxjvezotuq',
 'updated_at': '2020-01-05 13:42:18.823766',
 'url': 'https://api.chucknorris.io/jokes/fw_gwlvrsl-7fxjvezotuq',
 'value': "Chuck Norris doesn't believe in ravioli. He stuffs a live turtle with beef and smothers it in pig's blood."}

# OpenStreetMap

In [44]:
# Amenities
# https://wiki.openstreetmap.org/wiki/Key:amenity

overpass_url = "http://overpass-api.de/api/interpreter"

overpass_query = """
[out:json];
node["amenity"="cafe"]
  (40.420801, -3.694702,40.423754, -3.688167); 
out;
"""
response = requests.get(overpass_url, 
                        params={'data': overpass_query})
print(response)
data = response.json()

<Response [406]>

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [47]:
data

{'version': 0.6,
 'generator': 'Overpass API 0.7.62.8 e802775f',
 'osm3s': {'timestamp_osm_base': '2025-11-02T20:26:21Z',
  'copyright': 'The data included in this document is from www.openstreetmap.org. The data is made available under ODbL.'},
 'elements': [{'type': 'node',
   'id': 2977298934,
   'lat': 40.4210523,
   'lon': -3.689841,
   'tags': {'addr:city': 'Madrid',
    'addr:housenumber': '4',
    'addr:street': 'Calle de Villalar',
    'amenity': 'cafe',
    'cuisine': 'regional',
    'internet_access': 'yes',
    'name': 'Café Villalar',
    'phone': '+34 914358937',
    'website': 'https://cafeteriavillalar.eatbu.com/'}},
  {'type': 'node',
   'id': 3426617375,
   'lat': 40.4221948,
   'lon': -3.6923421,
   'tags': {'addr:housenumber': '21',
    'addr:street': 'Paseo de Recoletos',
    'amenity': 'cafe',
    'check_date': '2024-09-04',
    'name': 'Gran Café Gijón',
    'outdoor_seating': 'yes',
    'phone': '+34 915 215 425',
    'website': 'https://cafegijon.com/',
    'wheelchair': 'no',
    'wikidata': 'Q1025608',
    'wikipedia': 'es:Café Gijón'}},
  {'type': 'node',
   'id': 3426800312,
   'lat': 40.4232935,
   'lon': -3.6940419,
   'tags': {'addr:city': 'Madrid',
    'addr:housenumber': '12',
    'addr:postcode': '28004',
    'addr:street': 'Calle del Conde de Xiquena',
    'amenity': 'cafe',
    'cuisine': 'coffee_shop',
    'name': 'Altered'}},
  {'type': 'node',
   'id': 4703448419,
   'lat': 40.4229908,
   'lon': -3.6936524,
   'tags': {'addr:city': 'Madrid',
    'addr:housenumber': '6',
    'addr:postcode': '28004',
    'addr:street': 'Calle del Marqués de Monasterio',
    'amenity': 'cafe',
    'check_date': '2024-09-04',
    'contact:facebook': 'https://www.facebook.com/hermanasae',
    'contact:instagram': 'https://www.instagram.com/hermanasarce/',
    'cuisine': 'cake',
    'disused:amenity': 'restaurant',
    'name': 'Hermanas Arce',
    'old_name': 'Noteolvides',
    'opening_hours': 'Tu-Fr 09:00-17:00; Sa 09:30-17:30',
    'wheelchair': 'limited'}},
  {'type': 'node',
   'id': 4778747544,
   'lat': 40.4223247,
   'lon': -3.6909735,
   'tags': {'addr:city': 'Madrid',
    'addr:housenumber': '1',
    'addr:postcode': '28001',
    'addr:street': 'Calle de Recoletos',
    'amenity': 'cafe',
    'brand': 'Santagloria',
    'brand:wikidata': 'Q54606497',
    'contact:phone': '+34 914319000',
    'contact:website': 'https://www.santagloria.com',
    'name': 'Santagloria',
    'shop': 'bakery'}},
  {'type': 'node',
   'id': 9207850217,
   'lat': 40.4218751,
   'lon': -3.6901227,
   'tags': {'amenity': 'cafe', 'name': 'masticar'}},
  {'type': 'node',
   'id': 13114656901,
   'lat': 40.4228625,
   'lon': -3.6890506,
   'tags': {'amenity': 'cafe'}}]}

In [48]:
data.keys()

dict_keys(['version', 'generator', 'osm3s', 'elements'])

In [49]:
data['osm3s']

{'timestamp_osm_base': '2025-11-02T20:26:21Z',
 'copyright': 'The data included in this document is from www.openstreetmap.org. The data is made available under ODbL.'}

In [50]:
data.get('osm3s')

{'timestamp_osm_base': '2025-11-02T20:26:21Z',
 'copyright': 'The data included in this document is from www.openstreetmap.org. The data is made available under ODbL.'}

In [51]:
data['osm3s']['copyright']

'The data included in this document is from www.openstreetmap.org. The data is made available under ODbL.'

In [52]:
data.get("elements")[3]

{'type': 'node',
 'id': 4703448419,
 'lat': 40.4229908,
 'lon': -3.6936524,
 'tags': {'addr:city': 'Madrid',
  'addr:housenumber': '6',
  'addr:postcode': '28004',
  'addr:street': 'Calle del Marqués de Monasterio',
  'amenity': 'cafe',
  'check_date': '2024-09-04',
  'contact:facebook': 'https://www.facebook.com/hermanasae',
  'contact:instagram': 'https://www.instagram.com/hermanasarce/',
  'cuisine': 'cake',
  'disused:amenity': 'restaurant',
  'name': 'Hermanas Arce',
  'old_name': 'Noteolvides',
  'opening_hours': 'Tu-Fr 09:00-17:00; Sa 09:30-17:30',
  'wheelchair': 'limited'}}

In [53]:
data.get("elements")[0]['tags']['addr:street'] + " " + data.get("elements")[0]['tags']['addr:housenumber']

'Calle de Villalar 4'

In [54]:
for element in data['elements']:
    print(element)

{'type': 'node', 'id': 2977298934, 'lat': 40.4210523, 'lon': -3.689841, 'tags': {'addr:city': 'Madrid', 'addr:housenumber': '4', 'addr:street': 'Calle de Villalar', 'amenity': 'cafe', 'cuisine': 'regional', 'internet_access': 'yes', 'name': 'Café Villalar', 'phone': '+34 914358937', 'website': 'https://cafeteriavillalar.eatbu.com/'}}
{'type': 'node', 'id': 3426617375, 'lat': 40.4221948, 'lon': -3.6923421, 'tags': {'addr:housenumber': '21', 'addr:street': 'Paseo de Recoletos', 'amenity': 'cafe', 'check_date': '2024-09-04', 'name': 'Gran Café Gijón', 'outdoor_seating': 'yes', 'phone': '+34 915 215 425', 'website': 'https://cafegijon.com/', 'wheelchair': 'no', 'wikidata': 'Q1025608', 'wikipedia': 'es:Café Gijón'}}
{'type': 'node', 'id': 3426800312, 'lat': 40.4232935, 'lon': -3.6940419, 'tags': {'addr:city': 'Madrid', 'addr:housenumber': '12', 'addr:postcode': '28004', 'addr:street': 'Calle del Conde de Xiquena', 'amenity': 'cafe', 'cuisine': 'coffee_shop', 'name': 'Altered'}}
{'type': 'node', 'id': 4703448419, 'lat': 40.4229908, 'lon': -3.6936524, 'tags': {'addr:city': 'Madrid', 'addr:housenumber': '6', 'addr:postcode': '28004', 'addr:street': 'Calle del Marqués de Monasterio', 'amenity': 'cafe', 'check_date': '2024-09-04', 'contact:facebook': 'https://www.facebook.com/hermanasae', 'contact:instagram': 'https://www.instagram.com/hermanasarce/', 'cuisine': 'cake', 'disused:amenity': 'restaurant', 'name': 'Hermanas Arce', 'old_name': 'Noteolvides', 'opening_hours': 'Tu-Fr 09:00-17:00; Sa 09:30-17:30', 'wheelchair': 'limited'}}
{'type': 'node', 'id': 4778747544, 'lat': 40.4223247, 'lon': -3.6909735, 'tags': {'addr:city': 'Madrid', 'addr:housenumber': '1', 'addr:postcode': '28001', 'addr:street': 'Calle de Recoletos', 'amenity': 'cafe', 'brand': 'Santagloria', 'brand:wikidata': 'Q54606497', 'contact:phone': '+34 914319000', 'contact:website': 'https://www.santagloria.com', 'name': 'Santagloria', 'shop': 'bakery'}}
{'type': 'node', 'id': 9207850217, 'lat': 40.4218751, 'lon': -3.6901227, 'tags': {'amenity': 'cafe', 'name': 'masticar'}}
{'type': 'node', 'id': 13114656901, 'lat': 40.4228625, 'lon': -3.6890506, 'tags': {'amenity': 'cafe'}}

In [55]:
data['elements']

[{'type': 'node',
  'id': 2977298934,
  'lat': 40.4210523,
  'lon': -3.689841,
  'tags': {'addr:city': 'Madrid',
   'addr:housenumber': '4',
   'addr:street': 'Calle de Villalar',
   'amenity': 'cafe',
   'cuisine': 'regional',
   'internet_access': 'yes',
   'name': 'Café Villalar',
   'phone': '+34 914358937',
   'website': 'https://cafeteriavillalar.eatbu.com/'}},
 {'type': 'node',
  'id': 3426617375,
  'lat': 40.4221948,
  'lon': -3.6923421,
  'tags': {'addr:housenumber': '21',
   'addr:street': 'Paseo de Recoletos',
   'amenity': 'cafe',
   'check_date': '2024-09-04',
   'name': 'Gran Café Gijón',
   'outdoor_seating': 'yes',
   'phone': '+34 915 215 425',
   'website': 'https://cafegijon.com/',
   'wheelchair': 'no',
   'wikidata': 'Q1025608',
   'wikipedia': 'es:Café Gijón'}},
 {'type': 'node',
  'id': 3426800312,
  'lat': 40.4232935,
  'lon': -3.6940419,
  'tags': {'addr:city': 'Madrid',
   'addr:housenumber': '12',
   'addr:postcode': '28004',
   'addr:street': 'Calle del Conde de Xiquena',
   'amenity': 'cafe',
   'cuisine': 'coffee_shop',
   'name': 'Altered'}},
 {'type': 'node',
  'id': 4703448419,
  'lat': 40.4229908,
  'lon': -3.6936524,
  'tags': {'addr:city': 'Madrid',
   'addr:housenumber': '6',
   'addr:postcode': '28004',
   'addr:street': 'Calle del Marqués de Monasterio',
   'amenity': 'cafe',
   'check_date': '2024-09-04',
   'contact:facebook': 'https://www.facebook.com/hermanasae',
   'contact:instagram': 'https://www.instagram.com/hermanasarce/',
   'cuisine': 'cake',
   'disused:amenity': 'restaurant',
   'name': 'Hermanas Arce',
   'old_name': 'Noteolvides',
   'opening_hours': 'Tu-Fr 09:00-17:00; Sa 09:30-17:30',
   'wheelchair': 'limited'}},
 {'type': 'node',
  'id': 4778747544,
  'lat': 40.4223247,
  'lon': -3.6909735,
  'tags': {'addr:city': 'Madrid',
   'addr:housenumber': '1',
   'addr:postcode': '28001',
   'addr:street': 'Calle de Recoletos',
   'amenity': 'cafe',
   'brand': 'Santagloria',
   'brand:wikidata': 'Q54606497',
   'contact:phone': '+34 914319000',
   'contact:website': 'https://www.santagloria.com',
   'name': 'Santagloria',
   'shop': 'bakery'}},
 {'type': 'node',
  'id': 9207850217,
  'lat': 40.4218751,
  'lon': -3.6901227,
  'tags': {'amenity': 'cafe', 'name': 'masticar'}},
 {'type': 'node',
  'id': 13114656901,
  'lat': 40.4228625,
  'lon': -3.6890506,
  'tags': {'amenity': 'cafe'}}]

In [56]:
data['elements']

[{'type': 'node',
  'id': 2977298934,
  'lat': 40.4210523,
  'lon': -3.689841,
  'tags': {'addr:city': 'Madrid',
   'addr:housenumber': '4',
   'addr:street': 'Calle de Villalar',
   'amenity': 'cafe',
   'cuisine': 'regional',
   'internet_access': 'yes',
   'name': 'Café Villalar',
   'phone': '+34 914358937',
   'website': 'https://cafeteriavillalar.eatbu.com/'}},
 {'type': 'node',
  'id': 3426617375,
  'lat': 40.4221948,
  'lon': -3.6923421,
  'tags': {'addr:housenumber': '21',
   'addr:street': 'Paseo de Recoletos',
   'amenity': 'cafe',
   'check_date': '2024-09-04',
   'name': 'Gran Café Gijón',
   'outdoor_seating': 'yes',
   'phone': '+34 915 215 425',
   'website': 'https://cafegijon.com/',
   'wheelchair': 'no',
   'wikidata': 'Q1025608',
   'wikipedia': 'es:Café Gijón'}},
 {'type': 'node',
  'id': 3426800312,
  'lat': 40.4232935,
  'lon': -3.6940419,
  'tags': {'addr:city': 'Madrid',
   'addr:housenumber': '12',
   'addr:postcode': '28004',
   'addr:street': 'Calle del Conde de Xiquena',
   'amenity': 'cafe',
   'cuisine': 'coffee_shop',
   'name': 'Altered'}},
 {'type': 'node',
  'id': 4703448419,
  'lat': 40.4229908,
  'lon': -3.6936524,
  'tags': {'addr:city': 'Madrid',
   'addr:housenumber': '6',
   'addr:postcode': '28004',
   'addr:street': 'Calle del Marqués de Monasterio',
   'amenity': 'cafe',
   'check_date': '2024-09-04',
   'contact:facebook': 'https://www.facebook.com/hermanasae',
   'contact:instagram': 'https://www.instagram.com/hermanasarce/',
   'cuisine': 'cake',
   'disused:amenity': 'restaurant',
   'name': 'Hermanas Arce',
   'old_name': 'Noteolvides',
   'opening_hours': 'Tu-Fr 09:00-17:00; Sa 09:30-17:30',
   'wheelchair': 'limited'}},
 {'type': 'node',
  'id': 4778747544,
  'lat': 40.4223247,
  'lon': -3.6909735,
  'tags': {'addr:city': 'Madrid',
   'addr:housenumber': '1',
   'addr:postcode': '28001',
   'addr:street': 'Calle de Recoletos',
   'amenity': 'cafe',
   'brand': 'Santagloria',
   'brand:wikidata': 'Q54606497',
   'contact:phone': '+34 914319000',
   'contact:website': 'https://www.santagloria.com',
   'name': 'Santagloria',
   'shop': 'bakery'}},
 {'type': 'node',
  'id': 9207850217,
  'lat': 40.4218751,
  'lon': -3.6901227,
  'tags': {'amenity': 'cafe', 'name': 'masticar'}},
 {'type': 'node',
  'id': 13114656901,
  'lat': 40.4228625,
  'lon': -3.6890506,
  'tags': {'amenity': 'cafe'}}]

In [57]:
data['elements'][2]['tags']

{'addr:city': 'Madrid',
 'addr:housenumber': '12',
 'addr:postcode': '28004',
 'addr:street': 'Calle del Conde de Xiquena',
 'amenity': 'cafe',
 'cuisine': 'coffee_shop',
 'name': 'Altered'}

In [58]:
data['elements'][1]

{'type': 'node',
 'id': 3426617375,
 'lat': 40.4221948,
 'lon': -3.6923421,
 'tags': {'addr:housenumber': '21',
  'addr:street': 'Paseo de Recoletos',
  'amenity': 'cafe',
  'check_date': '2024-09-04',
  'name': 'Gran Café Gijón',
  'outdoor_seating': 'yes',
  'phone': '+34 915 215 425',
  'website': 'https://cafegijon.com/',
  'wheelchair': 'no',
  'wikidata': 'Q1025608',
  'wikipedia': 'es:Café Gijón'}}

In [59]:
pd.DataFrame(data['elements'])

,type,id,lat,lon,tags
0,node,2977298934,40.421052,-3.689841,"{'addr:city': 'Madrid', 'addr:housenumber': '4..."
1,node,3426617375,40.422195,-3.692342,"{'addr:housenumber': '21', 'addr:street': 'Pas..."
2,node,3426800312,40.423293,-3.694042,"{'addr:city': 'Madrid', 'addr:housenumber': '1..."
3,node,4703448419,40.422991,-3.693652,"{'addr:city': 'Madrid', 'addr:housenumber': '6..."
4,node,4778747544,40.422325,-3.690974,"{'addr:city': 'Madrid', 'addr:housenumber': '1..."
5,node,9207850217,40.421875,-3.690123,"{'amenity': 'cafe', 'name': 'masticar'}"
6,node,13114656901,40.422863,-3.689051,{'amenity': 'cafe'}

In [60]:
def json_to_dataframe(data_entrada):
    elements = data_entrada['elements']
    places = {'lat': [], 'lon': [], 'name': [], 'address': []}

    for i in elements:
        lalitude = i['lat']
        longitude = i['lon']
        name = i['tags'].get('name')
        street = i['tags'].get('addr:street', 'Sin calle')
        number = i['tags'].get('addr:housenumber', 0)
        
        places['lat'].append(lalitude)
        places['lon'].append(longitude)
        places['name'].append(name)
        places['address'].append(str(street) + ' ' + str(number))

    df = pd.DataFrame(places)
    return df

In [61]:
data['elements'][1]['tags']

{'addr:housenumber': '21',
 'addr:street': 'Paseo de Recoletos',
 'amenity': 'cafe',
 'check_date': '2024-09-04',
 'name': 'Gran Café Gijón',
 'outdoor_seating': 'yes',
 'phone': '+34 915 215 425',
 'website': 'https://cafegijon.com/',
 'wheelchair': 'no',
 'wikidata': 'Q1025608',
 'wikipedia': 'es:Café Gijón'}

In [62]:
df_return = json_to_dataframe(data)
df_return.head()

         lat       lon             name                            address
0  40.421052 -3.689841    Café Villalar                Calle de Villalar 4
1  40.422195 -3.692342  Gran Café Gijón              Paseo de Recoletos 21
2  40.423293 -3.694042          Altered      Calle del Conde de Xiquena 12
3  40.422991 -3.693652    Hermanas Arce  Calle del Marqués de Monasterio 6
4  40.422325 -3.690974      Santagloria               Calle de Recoletos 1

In [63]:
# lista_responses = [data1, data2, data3, data4]
# for data in lista_responses:
#     df_return = json_to_dataframe(data)
#     df_results = df_results.concat(df_return)

## Datos del espacio

In [45]:
'''
https://thespacedevs.com/llapi
https://ll.thespacedevs.com/2.2.0/swagger
'''
space_url = "http://ll.thespacedevs.com/2.2.0"

path = "/astronaut"

url_total = space_url + path

response = requests.get(url_total)

In [47]:
print(response.status_code)
type(response.content)
response.json()

200

{'count': 854,
 'next': 'https://ll.thespacedevs.com/2.2.0/astronaut/?limit=10&offset=10',
 'previous': None,
 'results': [{'id': 1,
   'url': 'https://ll.thespacedevs.com/2.2.0/astronaut/1/',
   'name': 'Thomas Pesquet',
   'status': {'id': 1, 'name': 'Active'},
   'type': {'id': 2, 'name': 'Government'},
   'in_space': False,
   'time_in_space': 'P396DT11H33M45S',
   'eva_time': 'P1DT15H54M',
   'age': 48,
   'date_of_birth': '1978-02-27',
   'date_of_death': None,
   'nationality': 'French',
   'bio': 'Thomas Gautier Pesquet is a French aerospace engineer, pilot, and European Space Agency astronaut. Pesquet was selected by ESA as a candidate in May 2009, and he successfully completed his basic training in November 2010. From November 2016 to June 2017, Pesquet was part of Expeditions 50 and 51 on the International Space Station as a flight engineer.',
   'twitter': 'https://twitter.com/Thom_astro',
   'instagram': 'https://instagram.com/thom_astro',
   'wiki': 'https://en.wikipedia.org/wiki/Thomas_Pesquet',
   'agency': {'id': 27,
    'url': 'https://ll.thespacedevs.com/2.2.0/agencies/27/',
    'name': 'European Space Agency',
    'featured': False,
    'type': 'Multinational',
    'country_code': 'FRA,ITA,DEU,ESP,CHE,GBR,AUT,SWE,PRT,NLD,HUN,POL,DNK,CZE,ROU,NOR,FIN,GRC,EST,IRL,LUX,BEL,SVN',
    'abbrev': 'ESA',
    'description': "The European Space Agency is an intergovernmental organisation of 22 member states. Established in 1975 and headquartered in Paris, France, ESA has a worldwide staff of about 2,000 employees.\r\n\r\nESA's space flight programme includes human spaceflight (mainly through participation in the International Space Station program); the launch and operation of unmanned exploration missions to other planets and the Moon; Earth observation, science and telecommunication; designing launch vehicles; and maintaining a major spaceport, the Guiana Space Centre at Kourou, French Guiana.",
    'administrator': 'Director General: Josef Aschbacher',
    'founding_year': '1975',
    'launchers': 'Ariane | Vega',
    'spacecraft': 'Space Rider',
    'parent': None,
    'image_url': 'https://thespacedevs-prod.nyc3.digitaloceanspaces.com/media/images/esa_patch_float_image_20250211192109.png',
    'logo_url': 'https://thespacedevs-prod.nyc3.digitaloceanspaces.com/media/images/european2520space2520agency_logo_20221130101442.png'},
   'profile_image': 'https://thespacedevs-prod.nyc3.digitaloceanspaces.com/media/images/thomas2520pesquet_image_20200102120546.jpeg',
   'profile_image_thumbnail': 'https://thespacedevs-prod.nyc3.digitaloceanspaces.com/media/images/255bauto255d__image_thumbnail_20240305190357.jpeg',
   'flights_count': 2,
   'landings_count': 2,
   'spacewalks_count': 6,
   'last_flight': '2021-04-23T09:49:02Z',
   'first_flight': '2016-11-17T20:20:13Z'},
  {'id': 2,
   'url': 'https://ll.thespacedevs.com/2.2.0/astronaut/2/',
   'name': 'Claude Nicollier',
   'status': {'id': 2, 'name': 'Retired'},
   'type': {'id': 2, 'name': 'Government'},
   'in_space': False,
   'time_in_space': 'P42DT12H3M12S',
   'eva_time': 'PT8H10M',
   'age': 81,
   'date_of_birth': '1944-09-02',
   'date_of_death': None,
   'nationality': 'Swiss',
   'bio': 'Claude Nicollier is the first astronaut from Switzerland. He has flown on four Space Shuttle missions. His first spaceflight (STS-46) was in 1992, and his final spaceflight (STS-103) was in 1999. He took part in two servicing missions to the Hubble Space Telescope (called STS-61 and STS-103). During his final spaceflight he participated in a spacewalk, becoming the first European Space Agency astronaut to do so during a Space Shuttle mission. In 2000 he was assigned to the Astronaut Office Extravehicular Activity Branch, while maintaining a position as Lead ESA Astronaut in Houston. Nicollier retired from ESA in April 2007.',
   'twitter': 'https://twitter.com/Astroclaude',
   'instagram': None,
   'wiki': 'https://en.wikipedia.org/wiki/Claude_Nicollier',
   'agency': {'id': 27,
    'url': 'https://ll.thespacedevs.com/2.2.0/agencies/27/',
    'name': 'European Space Agency',
    'featured': False,
    'type': 'Multinational',
    'country_code': 'FRA,ITA,DEU,ESP,CHE,GBR,AUT,SWE,PRT,NLD,HUN,POL,DNK,CZE,ROU,NOR,FIN,GRC,EST,IRL,LUX,BEL,SVN',
    'abbrev': 'ESA',
    'description': "The European Space Agency is an intergovernmental organisation of 22 member states. Established in 1975 and headquartered in Paris, France, ESA has a worldwide staff of about 2,000 employees.\r\n\r\nESA's space flight programme includes human spaceflight (mainly through participation in the International Space Station program); the launch and operation of unmanned exploration missions to other planets and the Moon; Earth observation, science and telecommunication; designing launch vehicles; and maintaining a major spaceport, the Guiana Space Centre at Kourou, French Guiana.",
    'administrator': 'Director General: Josef Aschbacher',
    'founding_year': '1975',
    'launchers': 'Ariane | Vega',
    'spacecraft': 'Space Rider',
    'parent': None,
    'image_url': 'https://thespacedevs-prod.nyc3.digitaloceanspaces.com/media/images/esa_patch_float_image_20250211192109.png',
    'logo_url': 'https://thespacedevs-prod.nyc3.digitaloceanspaces.com/media/images/european2520space2520agency_logo_20221130101442.png'},
   'profile_image': 'https://thespacedevs-prod.nyc3.digitaloceanspaces.com/media/images/claude2520nicollier_image_20181127203218.jpg',
   'profile_image_thumbnail': 'https://thespacedevs-prod.nyc3.digitaloceanspaces.com/media/images/255bauto255d__image_thumbnail_20240305185551.jpeg',
   'flights_count': 4,
   'landings_count': 4,
   'spacewalks_count': 1,
   'last_flight': '1999-12-20T00:50:00Z',
   'first_flight': '1992-07-31T13:56:48Z'},
  {'id': 3,
   'url': 'https://ll.thespacedevs.com/2.2.0/astronaut/3/',
   'name': 'Tim Peake',
   'status': {'id': 2, 'name': 'Retired'},
   'type': {'id': 2, 'name': 'Government'},
   'in_space': False,
   'time_in_space': 'P185DT22H11M51S',
   'eva_time': 'PT4H43M',
   'age': 54,
   'date_of_birth': '1972-04-07',
   'date_of_death': None,
   'nationality': 'British',
   'bio': "Major Timothy Nigel Peake CMG is a British Army Air Corps officer, former European Space Agency astronaut and International Space Station (ISS) crew member.  He is the first British ESA astronaut, the second astronaut to bear a flag of the United Kingdom patch, the sixth person born in the United Kingdom to go on board the International Space Station and the seventh UK-born person in space. He began the ESA's intensive astronaut basic training course in September 2009 and graduated on 22 November 2010",
   'twitter': 'https://twitter.com/astro_timpeake',
   'instagram': 'https://www.instagram.com/astro_timpeake/',
   'wiki': 'https://en.wikipedia.org/wiki/Tim_Peake',
   'agency': {'id': 27,
    'url': 'https://ll.thespacedevs.com/2.2.0/agencies/27/',
    'name': 'European Space Agency',
    'featured': False,
    'type': 'Multinational',
    'country_code': 'FRA,ITA,DEU,ESP,CHE,GBR,AUT,SWE,PRT,NLD,HUN,POL,DNK,CZE,ROU,NOR,FIN,GRC,EST,IRL,LUX,BEL,SVN',
    'abbrev': 'ESA',
    'description': "The European Space Agency is an intergovernmental organisation of 22 member states. Established in 1975 and headquartered in Paris, France, ESA has a worldwide staff of about 2,000 employees.\r\n\r\nESA's space flight programme includes human spaceflight (mainly through participation in the International Space Station program); the launch and operation of unmanned exploration missions to other planets and the Moon; Earth observation, science and telecommunication; designing launch vehicles; and maintaining a major spaceport, the Guiana Space Centre at Kourou, French Guiana.",
    'administrator': 'Director General: Josef Aschbacher',
    'founding_year': '1975',
    'launchers': 'Ariane | Vega',
    'spacecraft': 'Space Rider',
    'parent': None,
    'image_url': 'https://thespacedevs-prod.nyc3.digitaloceanspaces.com/media/images/esa_patch_float_image_20250211192109.png',
    'logo_url': 'https://thespacedevs-prod.nyc3.digitaloceanspaces.com/media/images/european2520space2520agency_logo_20221130101442.png'},
   'profile_image': 'https://thespacedevs-prod.nyc3.digitaloceanspaces.com/media/images/tim_peake_image_20230120154350.jpg',
   'profile_image_thumbnail': 'https://thespacedevs-prod.nyc3.digitaloceanspaces.com/media/images/255bauto255d__image_thumbnail_20240305185843.jpeg',
   'flights_count': 1,
   'landings_count': 1,
   'spacewalks_count': 1,
   'last_flight': '2015-12-15T11:03:09Z',
   'first_flight': '2015-12-15T11:03:09Z'},
  {'id': 4,
   'url': 'https://ll.thespacedevs.com/2.2.0/astronaut/4/',
   'name': 'Buzz Aldrin',
   'status': {'id': 2, 'name': 'Retired'},
   'type': {'id': 2, 'name': 'Government'},
   'in_space': False,
   'time_in_space': 'P9DT8H43M58S',
   'eva_time': 'PT8H1M40S',
   'age': 96,
   'date_of_birth': '1930-01-20',
   'date_of_death': None,
   'nationality': 'American',
   'bio': 'Buzz Aldrin; born Edwin Eugene Aldrin Jr.; is an American engineer, former astronaut, and fighter pilot.\r\nAs Lunar Module Pilot on the Apollo 11 mission, he and mission commander Neil Armstrong were the first two humans to land on the Moon.',
   'twitter': 'https://twitter.com/TheRealBuzz',
   'instagram': 'https://www.instagram.com/drbuzzaldrin/',
   'wiki': 'https://en.wikipedia.org/wiki/Buzz_Aldrin',
   'agency': {'id': 44,
    'url': 'https://ll.thespacedevs.com/2.2.0/agencies/44/',
    'name': 'National Aeronautics and Space Administration',
    'featured': True,
    'type': 'Government',
    'country_code': 'USA',
    'abbrev': 'NASA',
    'description': 'The National Aeronautics and Space Administration is an independent agency of the executive branch of the United States federal government responsible for the civilian space program, as well as aeronautics and aerospace research. NASA have many launch facilities but most are inactive. The most commonly used pad will be LC-39B at Kennedy Space Center in Florida.',
    'administrator': 'Administrator: Jared Isaacman',
    'founding_year': '1958',
    'launchers': 'Space Shuttle | SLS',
    'spacecraft': 'Orion',
    'parent': None,
    'image_url': 'https://thespacedevs-prod.nyc3.digitaloceanspaces.com/media/images/national2520aeronautics2520and2520space2520administration_image_20190207032448.jpeg',
    'logo_url': 'https://thespacedevs-prod.nyc3.digitaloceanspaces.com/media/images/national2520aeronautics2520and2520space2520administration_logo_20190207032448.png'},
   'profile_image': 'https://thespacedevs-prod.nyc3.digitaloceanspaces.com/media/images/buzz_aldrin_image_20220911034547.jpeg',
   'profile_image_thumbnail': 'https://thespacedevs-prod.nyc3.digitaloceanspaces.com/media/images/255bauto255d__image_thumbnail_20240305185225.jpeg',
   'flights_count': 2,
   'landings_count': 2,
   'spacewalks_count': 4,
   'last_flight': '1969-07-21T17:54:00Z',
   'first_flight': '1966-11-11T20:46:33Z'},
  {'id': 5,
   'url': 'https://ll.thespacedevs.com/2.2.0/astronaut/5/',
   'name': 'Chris Hadfield',
   'status': {'id': 2, 'name': 'Retired'},
   'type': {'id': 2, 'name': 'Government'},
   'in_space': False,
   'time_in_space': 'P165DT16H19M',
   'eva_time': 'PT14H50M',
   'age': 66,
   'date_of_birth': '1959-08-29',
   'date_of_death': None,
   'nationality': 'Canadian',
   'bio': 'Chris Austin Hadfield is a Canadian retired astronaut, engineer, and former Royal Canadian Air Force fighter pilot.\r\nThe first Canadian to walk in space, Hadfield has flown two space shuttle missions and served as commander of the International Space Station.',
   'twitter': 'https://twitter.com/Cmdr_Hadfield',
   'instagram': 'https://www.instagram.com/colchrishadfield/',
   'wiki': 'https://en.wikipedia.org/wiki/Chris_Hadfield',
   'agency': {'id': 16,
    'url': 'https://ll.thespacedevs.com/2.2.0/agencies/16/',
    'name': 'Canadian Space Agency',
    'featured': False,
    'type': 'Government',
    'country_code': 'CAN',
    'abbrev': 'CSA',
    'description': 'The Canadian Space Agency was established by the Canadian Space Agency Act which received Royal Assent on May 10, 1990. \r\n\r\nThe Canadian space program is administered by the Canadian Space Agency. Canada has contributed technology, expertise and personnel to the world space effort, especially in collaboration with ESA and NASA. In addition to its astronauts and satellites, some of the most notable Canadian technological contributions to space exploration include the Canadarm on the Space Shuttle and Canadarm2 on the International Space Station.',
    'administrator': 'President: Lisa Campbell',
    'founding_year': '1990',
    'launchers': '',
    'spacecraft': '',
    'parent': None,
    'image_url': None,
    'logo_url': 'https://thespacedevs-prod.nyc3.digitaloceanspaces.com/media/images/canadian_space__image_20260402074720.png'},
   'profile_image': 'https://thespacedevs-prod.nyc3.digitaloceanspaces.com/media/images/chris_hadfield_image_20220911034200.jpeg',
   'profile_image_thumbnail': 'https://thespacedevs-prod.nyc3.digitaloceanspaces.com/media/images/255bauto255d__image_thumbnail_20240305190208.jpeg',
   'flights_count': 3,
   'landings_count': 3,
   'spacewalks_count': 2,
   'last_flight': '2012-12-19T12:12:35Z',
   'first_flight': '1995-11-12T12:30:43Z'},
  {'id': 6,
   'url': 'https://ll.thespacedevs.com/2.2.0/astronaut/6/',
   'name': 'David Saint-Jacques',
   'status': {'id': 1, 'name': 'Active'},
   'type': {'id': 2, 'name': 'Government'},
   'in_space': False,
   'time_in_space': 'P203DT12H28M8S',
   'eva_time': 'PT6H29M',
   'age': 56,
   'date_of_birth': '1970-01-06',
   'date_of_death': None,
   'nationality': 'Canadian',
   'bio': 'David Saint-Jacques is a Canadian astronaut with the Canadian Space Agency (CSA).\r\nHe was also an engineer, an astrophysicist, and a physician prior to joining the CSA.\r\nHe was selected to join the CSA in the 2009 CSA selection along with Jeremy Hansen.',
   'twitter': 'https://twitter.com/Astro_DavidS',
   'instagram': 'https://www.instagram.com/astrodavids/',
   'wiki': 'https://en.wikipedia.org/wiki/David_Saint-Jacques',
   'agency': {'id': 16,
    'url': 'https://ll.thespacedevs.com/2.2.0/agencies/16/',
    'name': 'Canadian Space Agency',
    'featured': False,
    'type': 'Government',
    'country_code': 'CAN',
    'abbrev': 'CSA',
    'description': 'The Canadian Space Agency was established by the Canadian Space Agency Act which received Royal Assent on May 10, 1990. \r\n\r\nThe Canadian space program is administered by the Canadian Space Agency. Canada has contributed technology, expertise and personnel to the world space effort, especially in collaboration with ESA and NASA. In addition to its astronauts and satellites, some of the most notable Canadian technological contributions to space exploration include the Canadarm on the Space Shuttle and Canadarm2 on the International Space Station.',
    'administrator': 'President: Lisa Campbell',
    'founding_year': '1990',
    'launchers': '',
    'spacecraft': '',
    'parent': None,
    'image_url': None,
    'logo_url': 'https://thespacedevs-prod.nyc3.digitaloceanspaces.com/media/images/canadian_space__image_20260402074720.png'},
   'profile_image': 'https://thespacedevs-prod.nyc3.digitaloceanspaces.com/media/images/david_saint-jac_image_20220911034207.jpeg',
   'profile_image_thumbnail': 'https://thespacedevs-prod.nyc3.digitaloceanspaces.com/media/images/255bauto255d__image_thumbnail_20240305191004.jpeg',
   'flights_count': 1,
   'landings_count': 1,
   'spacewalks_count': 1,
   'last_flight': '2018-12-03T11:31:52Z',
   'first_flight': '2018-12-03T11:31:52Z'},
  {'id': 7,
   'url': 'https://ll.thespacedevs.com/2.2.0/astronaut/7/',
   'name': 'Anne McClain',
   'status': {'id': 1, 'name': 'Active'},
   'type': {'id': 2, 'name': 'Government'},
   'in_space': False,
   'time_in_space': 'P351DT4H57M40S',
   'eva_time': 'PT18H52M',
   'age': 46,
   'date_of_birth': '1979-06-07',
   'date_of_death': None,
   'nationality': 'American',
   'bio': 'Anne Charlotte McClain is a lieutenant colonel in the U.S. Army currently assigned to NASA Astronaut Group 21.',
   'twitter': 'https://twitter.com/AstroAnnimal',
   'instagram': None,
   'wiki': 'https://en.wikipedia.org/wiki/Anne_McClain',
   'agency': {'id': 44,
    'url': 'https://ll.thespacedevs.com/2.2.0/agencies/44/',
    'name': 'National Aeronautics and Space Administration',
    'featured': True,
    'type': 'Government',
    'country_code': 'USA',
    'abbrev': 'NASA',
    'description': 'The National Aeronautics and Space Administration is an independent agency of the executive branch of the United States federal government responsible for the civilian space program, as well as aeronautics and aerospace research. NASA have many launch facilities but most are inactive. The most commonly used pad will be LC-39B at Kennedy Space Center in Florida.',
    'administrator': 'Administrator: Jared Isaacman',
    'founding_year': '1958',
    'launchers': 'Space Shuttle | SLS',
    'spacecraft': 'Orion',
    'parent': None,
    'image_url': 'https://thespacedevs-prod.nyc3.digitaloceanspaces.com/media/images/national2520aeronautics2520and2520space2520administration_image_20190207032448.jpeg',
    'logo_url': 'https://thespacedevs-prod.nyc3.digitaloceanspaces.com/media/images/national2520aeronautics2520and2520space2520administration_logo_20190207032448.png'},
   'profile_image': 'https://thespacedevs-prod.nyc3.digitaloceanspaces.com/media/images/anne2520mcclain_image_20181127210625.jpg',
   'profile_image_thumbnail': 'https://thespacedevs-prod.nyc3.digitaloceanspaces.com/media/images/255bauto255d__image_thumbnail_20240305185442.jpeg',
   'flights_count': 2,
   'landings_count': 2,
   'spacewalks_count': 3,
   'last_flight': '2025-03-14T23:03:48Z',
   'first_flight': '2018-12-03T11:31:52Z'},
  {'id': 8,
   'url': 'https://ll.thespacedevs.com/2.2.0/astronaut/8/',
   'name': 'Andrew R. Morgan',
   'status': {'id': 1, 'name': 'Active'},
   'type': {'id': 2, 'name': 'Government'},
   'in_space': False,
   'time_in_space': 'P271DT12H48M22S',
   'eva_time': 'P1DT21H48M',
   'age': 50,
   'date_of_birth': '1976-02-05',
   'date_of_death': None,
   'nationality': 'American',
   'bio': 'Andrew Richard "Drew" Morgan is a NASA astronaut from the class of 2013.',
   'twitter': 'https://twitter.com/AstroDrewMorgan',
   'instagram': 'https://www.instagram.com/astrodrewmorgan/',
   'wiki': 'https://en.wikipedia.org/wiki/Andrew_R._Morgan',
   'agency': {'id': 44,
    'url': 'https://ll.thespacedevs.com/2.2.0/agencies/44/',
    'name': 'National Aeronautics and Space Administration',
    'featured': True,
    'type': 'Government',
    'country_code': 'USA',
    'abbrev': 'NASA',
    'description': 'The National Aeronautics and Space Administration is an independent agency of the executive branch of the United States federal government responsible for the civilian space program, as well as aeronautics and aerospace research. NASA have many launch facilities but most are inactive. The most commonly used pad will be LC-39B at Kennedy Space Center in Florida.',
    'administrator': 'Administrator: Jared Isaacman',
    'founding_year': '1958',
    'launchers': 'Space Shuttle | SLS',
    'spacecraft': 'Orion',
    'parent': None,
    'image_url': 'https://thespacedevs-prod.nyc3.digitaloceanspaces.com/media/images/national2520aeronautics2520and2520space2520administration_image_20190207032448.jpeg',
    'logo_url': 'https://thespacedevs-prod.nyc3.digitaloceanspaces.com/media/images/national2520aeronautics2520and2520space2520administration_logo_20190207032448.png'},
   'profile_image': 'https://thespacedevs-prod.nyc3.digitaloceanspaces.com/media/images/andrew_r._morga_image_20220911034204.jpeg',
   'profile_image_thumbnail': 'https://thespacedevs-prod.nyc3.digitaloceanspaces.com/media/images/255bauto255d__image_thumbnail_20240305185549.jpeg',
   'flights_count': 1,

In [48]:
url_total

'http://ll.thespacedevs.com/2.2.0/astronaut'

In [57]:
url_total = space_url + path + "/?search=armstrong"
print(url_total)
response_sp = requests.get(url_total)

http://ll.thespacedevs.com/2.2.0/astronaut/?search=armstrong

In [58]:
response_sp

In [71]:
url_total

'http://ll.thespacedevs.com/2.2.0/astronaut/?age=45'

In [50]:
response_sp.json()

{'count': 8,
 'next': None,
 'previous': None,
 'results': [{'id': 7,
   'url': 'https://ll.thespacedevs.com/2.2.0/astronaut/7/',
   'name': 'Anne McClain',
   'status': {'id': 1, 'name': 'Active'},
   'type': {'id': 2, 'name': 'Government'},
   'in_space': False,
   'time_in_space': 'P203DT12H28M8S',
   'eva_time': 'PT13H8M',
   'age': 45,
   'date_of_birth': '1979-06-07',
   'date_of_death': None,
   'nationality': 'American',
   'bio': 'Anne Charlotte McClain is a lieutenant colonel in the U.S. Army currently assigned to NASA Astronaut Group 21.',
   'twitter': 'https://twitter.com/AstroAnnimal',
   'instagram': None,
   'wiki': 'https://en.wikipedia.org/wiki/Anne_McClain',
   'agency': {'id': 44,
    'url': 'https://ll.thespacedevs.com/2.2.0/agencies/44/',
    'name': 'National Aeronautics and Space Administration',
    'featured': True,
    'type': 'Government',
    'country_code': 'USA',
    'abbrev': 'NASA',
    'description': 'The National Aeronautics and Space Administration is an independent agency of the executive branch of the United States federal government responsible for the civilian space program, as well as aeronautics and aerospace research. NASA have many launch facilities but most are inactive. The most commonly used pad will be LC-39B at Kennedy Space Center in Florida.',
    'administrator': 'Administrator: Bill Nelson',
    'founding_year': '1958',
    'launchers': 'Space Shuttle | SLS',
    'spacecraft': 'Orion',
    'parent': None,
    'image_url': 'https://thespacedevs-prod.nyc3.digitaloceanspaces.com/media/images/national2520aeronautics2520and2520space2520administration_image_20190207032448.jpeg',
    'logo_url': 'https://thespacedevs-prod.nyc3.digitaloceanspaces.com/media/images/national2520aeronautics2520and2520space2520administration_logo_20190207032448.png'},
   'profile_image': 'https://thespacedevs-prod.nyc3.digitaloceanspaces.com/media/images/anne2520mcclain_image_20181127210625.jpg',
   'profile_image_thumbnail': 'https://thespacedevs-prod.nyc3.digitaloceanspaces.com/media/images/255bauto255d__image_thumbnail_20240305185442.jpeg',
   'flights_count': 1,
   'landings_count': 1,
   'spacewalks_count': 2,
   'last_flight': '2018-12-03T11:31:52Z',
   'first_flight': '2018-12-03T11:31:52Z'},
  {'id': 86,
   'url': 'https://ll.thespacedevs.com/2.2.0/astronaut/86/',
   'name': 'Chen Dong',
   'status': {'id': 1, 'name': 'Active'},
   'type': {'id': 2, 'name': 'Government'},
   'in_space': False,
   'time_in_space': 'P214DT15H54M19S',
   'eva_time': 'PT15H53M',
   'age': 45,
   'date_of_birth': '1978-12-12',
   'date_of_death': None,
   'nationality': 'Chinese',
   'bio': "Chen Dong (simplified Chinese: 陈冬; traditional Chinese: 陳冬; pinyin: Chén Dōng; born 12 December 1978) is a Chinese pilot and astronaut selected as part of the Shenzhou program.\r\n\r\nHe was selected to fly on the Shenzhou 11 mission in October 2016 with astronaut Jing Haipeng. The two underwent more than 3,000 hours of training before the launch of the spacecraft. On 17 October 2016 On 07:30 local time (23:30 GMT on 16 October), Chen lifted off with Shenzhou 11 for a 33-day space mission to the Tiangong-2 space station as his first spaceflight, launched from the Jiuquan Satellite Launch Center using a Long March 2F launch rocket. The crew landed successfully after the 33 day mission on 18 November 2016, marking China's longest manned space flight to date. The reentry module of the Shenzhou-11 spacecraft landed in Inner Mongolia around 2.15 p.m(China time) after detaching from the space lab on 17 November.",
   'twitter': None,
   'instagram': None,
   'wiki': 'https://en.wikipedia.org/wiki/Chen_Dong_(astronaut)',
   'agency': {'id': 17,
    'url': 'https://ll.thespacedevs.com/2.2.0/agencies/17/',
    'name': 'China National Space Administration',
    'featured': True,
    'type': 'Government',
    'country_code': 'CHN',
    'abbrev': 'CNSA',
    'description': "The China National Space Administration (CNSA) is the national space agency of the People's Republic of China. It is responsible for the national space program and for planning and development of space activities. CNSA and China Aerospace Corporation (CASC) assumed the authority over space development efforts previously held by the Ministry of Aerospace Industry. The CNSA has many launch sites around China with their orbital sites located in Jiuquan, Xichang, Taiyuan and Wenchang.",
    'administrator': 'Administrator: Tang Dengjie',
    'founding_year': '1993',
    'launchers': '',
    'spacecraft': 'Shenzhou',
    'parent': None,
    'image_url': 'https://thespacedevs-prod.nyc3.digitaloceanspaces.com/media/images/china2520national2520space2520administration_image_20190207032431.jpeg',
    'logo_url': 'https://thespacedevs-prod.nyc3.digitaloceanspaces.com/media/images/china2520national2520space2520administration_logo_20190207032431.png'},
   'profile_image': 'https://thespacedevs-prod.nyc3.digitaloceanspaces.com/media/images/chen_dong_image_20220604084758.png',
   'profile_image_thumbnail': 'https://thespacedevs-prod.nyc3.digitaloceanspaces.com/media/images/255bauto255d__image_thumbnail_20240305190228.png',
   'flights_count': 2,
   'landings_count': 2,
   'spacewalks_count': 3,
   'last_flight': '2022-06-05T02:44:10Z',
   'first_flight': '2016-10-16T23:30:31Z'},
  {'id': 152,
   'url': 'https://ll.thespacedevs.com/2.2.0/astronaut/152/',
   'name': 'Rick Husband',
   'status': {'id': 4, 'name': 'Lost In Flight'},
   'type': {'id': 2, 'name': 'Government'},
   'in_space': False,
   'time_in_space': 'P25DT17H32M18S',
   'eva_time': 'P0D',
   'age': 45,
   'date_of_birth': '1957-07-12',
   'date_of_death': '2003-02-01',
   'nationality': 'American',
   'bio': "Rick Douglas Husband (July 12, 1957 – February 1, 2003) (Colonel, USAF) was an American astronaut and fighter pilot. He traveled into space twice: as Pilot of STS-96 and Commander of STS-107. He and the rest of the crew of STS-107 were killed when Columbia disintegrated during reentry into the Earth's atmosphere.",
   'twitter': None,
   'instagram': None,
   'wiki': 'https://en.wikipedia.org/wiki/Rick_Husband',
   'agency': {'id': 44,
    'url': 'https://ll.thespacedevs.com/2.2.0/agencies/44/',
    'name': 'National Aeronautics and Space Administration',
    'featured': True,
    'type': 'Government',
    'country_code': 'USA',
    'abbrev': 'NASA',
    'description': 'The National Aeronautics and Space Administration is an independent agency of the executive branch of the United States federal government responsible for the civilian space program, as well as aeronautics and aerospace research. NASA have many launch facilities but most are inactive. The most commonly used pad will be LC-39B at Kennedy Space Center in Florida.',
    'administrator': 'Administrator: Bill Nelson',
    'founding_year': '1958',
    'launchers': 'Space Shuttle | SLS',
    'spacecraft': 'Orion',
    'parent': None,
    'image_url': 'https://thespacedevs-prod.nyc3.digitaloceanspaces.com/media/images/national2520aeronautics2520and2520space2520administration_image_20190207032448.jpeg',
    'logo_url': 'https://thespacedevs-prod.nyc3.digitaloceanspaces.com/media/images/national2520aeronautics2520and2520space2520administration_logo_20190207032448.png'},
   'profile_image': 'https://thespacedevs-prod.nyc3.digitaloceanspaces.com/media/images/rick2520husband_image_20181129211548.jpg',
   'profile_image_thumbnail': 'https://thespacedevs-prod.nyc3.digitaloceanspaces.com/media/images/255bauto255d__image_thumbnail_20240305185435.jpeg',
   'flights_count': 2,
   'landings_count': 2,
   'spacewalks_count': 0,
   'last_flight': '2003-01-16T15:39:00Z',
   'first_flight': '1999-05-27T10:49:42Z'},
  {'id': 565,
   'url': 'https://ll.thespacedevs.com/2.2.0/astronaut/565/',
   'name': 'Kathleen Rubins',
   'status': {'id': 1, 'name': 'Active'},
   'type': {'id': 2, 'name': 'Government'},
   'in_space': False,
   'time_in_space': 'P300DT1H31M16S',
   'eva_time': 'P1DT3H3M',
   'age': 45,
   'date_of_birth': '1978-10-14',
   'date_of_death': None,
   'nationality': 'American',
   'bio': 'Kathleen Hallisey "Kate" Rubins is a NASA astronaut. She became the 60th woman to fly in space when she launched on a Soyuz spacecraft to the International Space Station on July 6, 2016. She returned to Earth on October 30, 2016 aboard a Soyuz. She was a crew member of Expedition 48 and Expedition 49 of the International Space Station.',
   'twitter': None,
   'instagram': None,
   'wiki': 'https://en.wikipedia.org/wiki/Kathleen_Rubins',
   'agency': {'id': 44,
    'url': 'https://ll.thespacedevs.com/2.2.0/agencies/44/',
    'name': 'National Aeronautics and Space Administration',
    'featured': True,
    'type': 'Government',
    'country_code': 'USA',
    'abbrev': 'NASA',
    'description': 'The National Aeronautics and Space Administration is an independent agency of the executive branch of the United States federal government responsible for the civilian space program, as well as aeronautics and aerospace research. NASA have many launch facilities but most are inactive. The most commonly used pad will be LC-39B at Kennedy Space Center in Florida.',
    'administrator': 'Administrator: Bill Nelson',
    'founding_year': '1958',
    'launchers': 'Space Shuttle | SLS',
    'spacecraft': 'Orion',
    'parent': None,
    'image_url': 'https://thespacedevs-prod.nyc3.digitaloceanspaces.com/media/images/national2520aeronautics2520and2520space2520administration_image_20190207032448.jpeg',
    'logo_url': 'https://thespacedevs-prod.nyc3.digitaloceanspaces.com/media/images/national2520aeronautics2520and2520space2520administration_logo_20190207032448.png'},
   'profile_image': 'https://thespacedevs-prod.nyc3.digitaloceanspaces.com/media/images/kathleen2520rubins_image_20181203172435.jpg',
   'profile_image_thumbnail': 'https://thespacedevs-prod.nyc3.digitaloceanspaces.com/media/images/255bauto255d__image_thumbnail_20240305185423.jpeg',
   'flights_count': 2,
   'landings_count': 2,
   'spacewalks_count': 4,
   'last_flight': '2020-10-14T05:45:04Z',
   'first_flight': '2016-07-07T01:36:40Z'},
  {'id': 635,
   'url': 'https://ll.thespacedevs.com/2.2.0/astronaut/635/',
   'name': 'Christina Koch',
   'status': {'id': 1, 'name': 'Active'},
   'type': {'id': 2, 'name': 'Government'},
   'in_space': False,
   'time_in_space': 'P328DT13H58M37S',
   'eva_time': 'P1DT18H15M',
   'age': 45,
   'date_of_birth': '1979-01-29',
   'date_of_death': None,
   'nationality': 'American',
   'bio': 'Christina Hammock Koch (born January 29, 1979) is a NASA astronaut of the class of 2013.',
   'twitter': 'https://twitter.com/Astro_Christina',
   'instagram': 'https://www.instagram.com/Astro_Christina/',
   'wiki': 'https://en.wikipedia.org/wiki/Christina_Koch',
   'agency': {'id': 44,
    'url': 'https://ll.thespacedevs.com/2.2.0/agencies/44/',
    'name': 'National Aeronautics and Space Administration',
    'featured': True,
    'type': 'Government',
    'country_code': 'USA',
    'abbrev': 'NASA',
    'description': 'The National Aeronautics and Space Administration is an independent agency of the executive branch of the United States federal government responsible for the civilian space program, as well as aeronautics and aerospace research. NASA have many launch facilities but most are inactive. The most commonly used pad will be LC-39B at Kennedy Space Center in Florida.',
    'administrator': 'Administrator: Bill Nelson',
    'founding_year': '1958',
    'launchers': 'Space Shuttle | SLS',
    'spacecraft': 'Orion',
    'parent': None,
    'image_url': 'https://thespacedevs-prod.nyc3.digitaloceanspaces.com/media/images/national2520aeronautics2520and2520space2520administration_image_20190207032448.jpeg',
    'logo_url': 'https://thespacedevs-prod.nyc3.digitaloceanspaces.com/media/images/national2520aeronautics2520and2520space2520administration_logo_20190207032448.png'},
   'profile_image': 'https://thespacedevs-prod.nyc3.digitaloceanspaces.com/media/images/christina2520koch_image_20191231114328.jpeg',
   'profile_image_thumbnail': 'https://thespacedevs-prod.nyc3.digitaloceanspaces.com/media/images/255bauto255d__image_thumbnail_20240305185818.jpeg',
   'flights_count': 1,
   'landings_count': 1,
   'spacewalks_count': 6,
   'last_flight': '2019-03-14T19:14:08Z',
   'first_flight': '2019-03-14T19:14:08Z'},
  {'id': 648,
   'url': 'https://ll.thespacedevs.com/2.2.0/astronaut/648/',
   'name': 'Joseph A. Walker',
   'status': {'id': 11, 'name': 'Deceased'},
   'type': {'id': 2, 'name': 'Government'},
   'in_space': False,
   'time_in_space': 'PT2H32M32S',
   'eva_time': 'P0D',
   'age': 45,
   'date_of_birth': '1921-02-20',
   'date_of_death': '1966-06-08',
   'nationality': 'American',
   'bio': 'Joseph Albert Walker was an American World War II pilot, experimental physicist, NASA test pilot, and astronaut. He was one of twelve pilots who flew the North American X-15, an experimental spaceplane jointly operated by the Air Force and NASA.',
   'twitter': None,
   'instagram': None,
   'wiki': 'https://en.wikipedia.org/wiki/Joseph_A._Walker',
   'agency': {'id': 44,
    'url': 'https://ll.thespacedevs.com/2.2.0/agencies/44/',
    'name': 'National Aeronautics and Space Administration',
    'featured': True,
    'type': 'Government',
    'country_code': 'USA',
    'abbrev': 'NASA',
    'description': 'The National Aeronautics and Space Administration is an independent agency of the executive branch of the United States federal government responsible for the civilian space program, as well as aeronautics and aerospace research. NASA have many launch facilities but most are inactive. The most commonly used pad will be LC-39B at Kennedy Space Center in Florida.',
    'administrator': 'Administrator: Bill Nelson',
    'founding_year': '1958',
    'launchers': 'Space Shuttle | SLS',
    'spacecraft': 'Orion',
    'parent': None,
    'image_url': 'https://thespacedevs-prod.nyc3.digitaloceanspaces.com/media/images/national2520aeronautics2520and2520space2520administration_image_20190207032448.jpeg',
    'logo_url': 'https://thespacedevs-prod.nyc3.digitaloceanspaces.com/media/images/national2520aeronautics2520and2520space2520administration_logo_20190207032448.png'},
   'profile_image': 'https://thespacedevs-prod.nyc3.digitaloceanspaces.com/media/images/joseph_a._walke_image_20200711033534.jpg',
   'profile_image_thumbnail': 'https://thespacedevs-prod.nyc3.digitaloceanspaces.com/media/images/255bauto255d__image_thumbnail_20240305185351.jpeg',
   'flights_count': 3,
   'landings_count': 3,
   'spacewalks_count': 0,
   'last_flight': '1963-08-22T18:05:57Z',
   'first_flight': '1963-01-17T16:59:00Z'},
  {'id': 661,
   'url': 'https://ll.thespacedevs.com/2.2.0/astronaut/661/',
   'name': 'Chris Sembroski',
   'status': {'id': 14, 'name': 'Occasional Spaceflight'},
   'type': {'id': 3, 'name': 'Private'},
   'in_space': False,
   'time_in_space': 'P3DT23H4M4S',
   'eva_time': 'P0D',
   'age': 45,
   'date_of_birth': '1979-08-28',
   'date_of_death': None,
   'nationality': 'American',
   'bio': 'Chris Sembroski is an aerospace worker at Lockheed Martin who used to work on Minuteman missiles in the Air Force.\r\n\r\nBirth date is unknown.',
   'twitter': 'https://twitter.com/epathctocs',
   'instagram': None,
   'wiki': 'https://en.wikipedia.org/wiki/Christopher_Sembroski',
   'agency': {'id': 121,
    'url': 'https://ll.thespacedevs.com/2.2.0/agencies/121/',
    'name': 'SpaceX',
    'featured': True,
    'type': 'Commercial',
    'country_code': 'USA',
    'abbrev': 'SpX',
    'description': 'Space Exploration Technologies Corp., known as SpaceX, is an American aerospace manufacturer and space transport services company headquartered in Hawthorne, California. It was founded in 2002 by entrepreneur Elon Musk with the goal of reducing space transportation costs and enabling the colonization of Mars. SpaceX operates from many pads, on the East Coast of the US they operate from SLC-40 at Cape Canaveral Space Force Station and historic LC-39A at Kennedy Space Center. They also operate from SLC-4E at Vandenberg Space Force Base, California, usually for polar launches. Another launch site is being developed at Boca Chica, Texas.',
    'administrator': 'CEO: Elon Musk',
    'founding_year': '2002',
    'launchers': 'Falcon | Starship',
    'spacecraft': 'Dragon',
    'parent': None,
    'image_url': 'https://thespacedevs-prod.nyc3.digitaloceanspaces.com/media/images/spacex_image_20190207032501.jpeg',
    'logo_url': 'https://thespacedevs-prod.nyc3.digitaloceanspaces.com/media/images/spacex_logo_20220826094919.png'},
   'profile_image': 'https://thespacedevs-prod.nyc3.digitaloceanspaces.com/media/images/chris_sembroski_image_20210914154201.jpeg',
   'profile_image_thumbnail': 'https://thespacedevs-prod.nyc3.digitaloceanspaces.com/media/images/255bauto255d__image_thumbnail_20240305185829.jpeg',
   'flights_count': 1,
   'landings_count': 1,
   'spacewalks_count': 0,
   'last_flight': '2021-09-16T00:02:56Z',
   'first_flight': '2021-09-16T00:02:56Z'},
  {'id': 710,
   'url': 'https://ll.thespacedevs.com/2.2.0/astronaut/710/',
   'name': 'Luke Delaney',
   'status': {'id': 3, 'name': 'In-Training'},
   'type': {'id': 2, 'name': 'Government'},
   'in_space': False,
   'time_in_space': 'P0D',
   'eva_time': 'P0D',
   'age': 45,
   'date_of_birth': '1979-01-01',
   'date_of_death': None,
   'nationality': 'American',
   'bio': 'Luke Delaney is a retired US Marine Corps major who grew up in Debary, Florida. He holds a degree in mechanical engineering from University of North Florida and a master’s degree in aerospace engineering from the Naval Postgraduate School. He is a distinguished naval aviator who participated in exercises throughout the Asia Pacific region and conducted combat missions in support of Operation Enduring Freedom. As a test pilot, he executed numerous flights evaluating weapon systems integration, and he served as a test pilot instructor. Delaney most recently worked as a research pilot at NASA’s Langley Research Center, in Hampton, Virginia, where he supported airborne science missions. Including his NASA career, Delaney logged more than 3,700 flight hours on 48 models of jet, propeller, and rotary wing aircraft.\r\n\r\nExact date of birth unknown.',
   'twitter': None,
   'instagram': None,
   'wiki': 'https://en.wikipedia.org/wiki/Luke_Delaney_(astronaut)',
   'agency': {'id': 44,
    'url': 'https://ll.thespacedevs.com/2.2.0/agencies/44/',
    'name': 'National Aeronautics and Space Administration',
    'featured': True,
    'type': 'Government',
    'country_code': 'USA',
    'abbrev': 'NASA',
    'description': 'The National Aeronautics and Space Administration is an independent agency of the executive branch of the United States federal government responsible for the civilian space program, as well as aeronautics and aerospace research. NASA have many launch facilities but most are inactive. The most commonly used pad will be LC-39B at Kennedy Space Center in Florida.',
    'administrator': 'Administrator: Bill Nelson',
    'founding_year': '1958',
    'launchers': 'Space Shuttle | SLS',
    'spacecraft': 'Orion',
    'parent': None,
    'image_url': 'https://thespacedevs-prod.nyc3.digitaloceanspaces.com/media/images/national2520aeronautics2520and2520space2520administration_image_20190207032448.jpeg',
    'logo_url': 'https://thespacedevs-prod.nyc3.digitaloceanspaces.com/media/images/national2520aeronautics2520and2520space2520administration_logo_20190207032448.png'},
   'profile_image': 'https://thespacedevs-prod.nyc3.digitaloceanspaces.com/media/images/luke_delaney_image_20211206185357.jpg',
   'profile_image_thumbnail': 'https://thespacedevs-prod.nyc3.digitaloceanspaces.com/media/images/255bauto255d__image_thumbnail_20240305190723.jpeg',
   'flights_count': 0,
   'landings_count': 0,
   'spacewalks_count': 0,
   'last_flight': None,
   'first_flight': None}]}

In [51]:
pd.DataFrame(response_sp.json()['results'])

,id,url,name,status,type,in_space,time_in_space,eva_time,age,date_of_birth,...,instagram,wiki,agency,profile_image,profile_image_thumbnail,flights_count,landings_count,spacewalks_count,last_flight,first_flight
0,7,https://ll.thespacedevs.com/2.2.0/astronaut/7/,Anne McClain,"{'id': 1, 'name': 'Active'}","{'id': 2, 'name': 'Government'}",False,P203DT12H28M8S,PT13H8M,45,1979-06-07,...,None,https://en.wikipedia.org/wiki/Anne_McClain,"{'id': 44, 'url': 'https://ll.thespacedevs.com...",https://thespacedevs-prod.nyc3.digitaloceanspa...,https://thespacedevs-prod.nyc3.digitaloceanspa...,1,1,2,2018-12-03T11:31:52Z,2018-12-03T11:31:52Z
1,86,https://ll.thespacedevs.com/2.2.0/astronaut/86/,Chen Dong,"{'id': 1, 'name': 'Active'}","{'id': 2, 'name': 'Government'}",False,P214DT15H54M19S,PT15H53M,45,1978-12-12,...,None,https://en.wikipedia.org/wiki/Chen_Dong_(astro...,"{'id': 17, 'url': 'https://ll.thespacedevs.com...",https://thespacedevs-prod.nyc3.digitaloceanspa...,https://thespacedevs-prod.nyc3.digitaloceanspa...,2,2,3,2022-06-05T02:44:10Z,2016-10-16T23:30:31Z
2,152,https://ll.thespacedevs.com/2.2.0/astronaut/152/,Rick Husband,"{'id': 4, 'name': 'Lost In Flight'}","{'id': 2, 'name': 'Government'}",False,P25DT17H32M18S,P0D,45,1957-07-12,...,None,https://en.wikipedia.org/wiki/Rick_Husband,"{'id': 44, 'url': 'https://ll.thespacedevs.com...",https://thespacedevs-prod.nyc3.digitaloceanspa...,https://thespacedevs-prod.nyc3.digitaloceanspa...,2,2,0,2003-01-16T15:39:00Z,1999-05-27T10:49:42Z
3,565,https://ll.thespacedevs.com/2.2.0/astronaut/565/,Kathleen Rubins,"{'id': 1, 'name': 'Active'}","{'id': 2, 'name': 'Government'}",False,P300DT1H31M16S,P1DT3H3M,45,1978-10-14,...,None,https://en.wikipedia.org/wiki/Kathleen_Rubins,"{'id': 44, 'url': 'https://ll.thespacedevs.com...",https://thespacedevs-prod.nyc3.digitaloceanspa...,https://thespacedevs-prod.nyc3.digitaloceanspa...,2,2,4,2020-10-14T05:45:04Z,2016-07-07T01:36:40Z
4,635,https://ll.thespacedevs.com/2.2.0/astronaut/635/,Christina Koch,"{'id': 1, 'name': 'Active'}","{'id': 2, 'name': 'Government'}",False,P328DT13H58M37S,P1DT18H15M,45,1979-01-29,...,https://www.instagram.com/Astro_Christina/,https://en.wikipedia.org/wiki/Christina_Koch,"{'id': 44, 'url': 'https://ll.thespacedevs.com...",https://thespacedevs-prod.nyc3.digitaloceanspa...,https://thespacedevs-prod.nyc3.digitaloceanspa...,1,1,6,2019-03-14T19:14:08Z,2019-03-14T19:14:08Z
5,648,https://ll.thespacedevs.com/2.2.0/astronaut/648/,Joseph A. Walker,"{'id': 11, 'name': 'Deceased'}","{'id': 2, 'name': 'Government'}",False,PT2H32M32S,P0D,45,1921-02-20,...,None,https://en.wikipedia.org/wiki/Joseph_A._Walker,"{'id': 44, 'url': 'https://ll.thespacedevs.com...",https://thespacedevs-prod.nyc3.digitaloceanspa...,https://thespacedevs-prod.nyc3.digitaloceanspa...,3,3,0,1963-08-22T18:05:57Z,1963-01-17T16:59:00Z
6,661,https://ll.thespacedevs.com/2.2.0/astronaut/661/,Chris Sembroski,"{'id': 14, 'name': 'Occasional Spaceflight'}","{'id': 3, 'name': 'Private'}",False,P3DT23H4M4S,P0D,45,1979-08-28,...,None,https://en.wikipedia.org/wiki/Christopher_Semb...,"{'id': 121, 'url': 'https://ll.thespacedevs.co...",https://thespacedevs-prod.nyc3.digitaloceanspa...,https://thespacedevs-prod.nyc3.digitaloceanspa...,1,1,0,2021-09-16T00:02:56Z,2021-09-16T00:02:56Z
7,710,https://ll.thespacedevs.com/2.2.0/astronaut/710/,Luke Delaney,"{'id': 3, 'name': 'In-Training'}","{'id': 2, 'name': 'Government'}",False,P0D,P0D,45,1979-01-01,...,None,https://en.wikipedia.org/wiki/Luke_Delaney_(as...,"{'id': 44, 'url': 'https://ll.thespacedevs.com...",https://thespacedevs-prod.nyc3.digitaloceanspa...,https://thespacedevs-prod.nyc3.digitaloceanspa...,0,0,0,None,None