# Ex - GroupBy

In [1]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/drinks.csv).

### Step 3. Assign it to a variable called drinks.

In [19]:
df = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/drinks.csv")
df.head(20)

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,AS
1,Albania,89,132,54,4.9,EU
2,Algeria,25,0,14,0.7,AF
3,Andorra,245,138,312,12.4,EU
4,Angola,217,57,45,5.9,AF
5,Antigua & Barbuda,102,128,45,4.9,NaN
6,Argentina,193,25,221,8.3,SA
7,Armenia,21,179,11,3.8,EU
8,Australia,261,72,212,10.4,OC
9,Austria,279,75,191,9.7,EU
10,Azerbaijan,21,46,5,1.3,EU
11,Bahamas,122,176,51,6.3,NaN
12,Bahrain,42,63,7,2.0,AS
13,Bangladesh,0,0,0,0.0,AS
14,Barbados,143,173,36,6.3,NaN
15,Belarus,142,373,42,14.4,EU
16,Belgium,295,84,212,10.5,EU
17,Belize,263,114,8,6.8,NaN
18,Benin,34,4,13,1.1,AF
19,Bhutan,23,0,0,0.4,AS

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 193 entries, 0 to 192
Data columns (total 6 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   country                       193 non-null    object
 1   beer_servings                 193 non-null    int64
 2   spirit_servings               193 non-null    int64
 3   wine_servings                 193 non-null    int64
 4   total_litres_of_pure_alcohol  193 non-null    float64
 5   continent                     170 non-null    object
dtypes: float64(1), int64(3), object(2)
memory usage: 9.2+ KB

In [5]:
df.describe()

,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol
count,193.000000,193.000000,193.000000,193.000000
mean,106.160622,80.994819,49.450777,4.717098
std,101.143103,88.284312,79.697598,3.773298
min,0.000000,0.000000,0.000000,0.000000
25%,20.000000,4.000000,1.000000,1.300000
50%,76.000000,56.000000,8.000000,4.200000
75%,188.000000,128.000000,59.000000,7.200000
max,376.000000,438.000000,370.000000,14.400000

### Step 4. Which continent drinks more beer on average?

In [6]:
df.head()

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,AS
1,Albania,89,132,54,4.9,EU
2,Algeria,25,0,14,0.7,AF
3,Andorra,245,138,312,12.4,EU
4,Angola,217,57,45,5.9,AF

In [7]:
df["continent"].value_counts()

continent
AF    53
EU    45
AS    44
OC    16
SA    12
Name: count, dtype: int64

In [16]:
df[df["continent"] == "NA"]

Empty DataFrame
Columns: [country, beer_servings, spirit_servings, wine_servings, total_litres_of_pure_alcohol, continent]
Index: []

In [15]:
df.groupby("continent")["beer_servings"].count().sum()

np.int64(170)

In [9]:
df.groupby("continent")["beer_servings"].mean().idxmax()

'EU'

In [12]:
df[df["continent"].isnull()]

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
5,Antigua & Barbuda,102,128,45,4.9,NaN
11,Bahamas,122,176,51,6.3,NaN
14,Barbados,143,173,36,6.3,NaN
17,Belize,263,114,8,6.8,NaN
32,Canada,240,122,100,8.2,NaN
41,Costa Rica,149,87,11,4.4,NaN
43,Cuba,93,137,5,4.2,NaN
50,Dominica,52,286,26,6.6,NaN
51,Dominican Republic,193,147,9,6.2,NaN
54,El Salvador,52,69,2,2.2,NaN
68,Grenada,199,438,28,11.9,NaN
69,Guatemala,53,69,2,2.2,NaN
73,Haiti,1,326,1,5.9,NaN
74,Honduras,69,98,2,3.0,NaN
84,Jamaica,82,97,9,3.4,NaN
109,Mexico,238,68,5,5.5,NaN
122,Nicaragua,78,118,1,3.5,NaN
130,Panama,285,104,18,7.2,NaN
143,St. Kitts & Nevis,194,205,32,7.7,NaN
144,St. Lucia,171,315,71,10.1,NaN
145,St. Vincent & the Grenadines,120,221,11,6.3,NaN
174,Trinidad & Tobago,197,156,7,6.4,NaN
184,USA,249,158,84,8.7,NaN

In [21]:
df.loc[df["continent"].isnull(), "continent"] = "NA"
df.head(20)

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,AS
1,Albania,89,132,54,4.9,EU
2,Algeria,25,0,14,0.7,AF
3,Andorra,245,138,312,12.4,EU
4,Angola,217,57,45,5.9,AF
5,Antigua & Barbuda,102,128,45,4.9,NA
6,Argentina,193,25,221,8.3,SA
7,Armenia,21,179,11,3.8,EU
8,Australia,261,72,212,10.4,OC
9,Austria,279,75,191,9.7,EU
10,Azerbaijan,21,46,5,1.3,EU
11,Bahamas,122,176,51,6.3,NA
12,Bahrain,42,63,7,2.0,AS
13,Bangladesh,0,0,0,0.0,AS
14,Barbados,143,173,36,6.3,NA
15,Belarus,142,373,42,14.4,EU
16,Belgium,295,84,212,10.5,EU
17,Belize,263,114,8,6.8,NA
18,Benin,34,4,13,1.1,AF
19,Bhutan,23,0,0,0.4,AS

In [23]:
df["continent"].value_counts()

continent
AF    53
EU    45
AS    44
NA    23
OC    16
SA    12
Name: count, dtype: int64

In [24]:
df.groupby("continent")["beer_servings"].mean().idxmax()

'EU'

### Step 5. For each continent print the statistics for wine consumption.

In [25]:
df.groupby("continent")["wine_servings"].describe()

           count        mean        std  min   25%    50%     75%    max
continent
AF          53.0   16.264151  38.846419  0.0   1.0    2.0   13.00  233.0
AS          44.0    9.068182  21.667034  0.0   0.0    1.0    8.00  123.0
EU          45.0  142.222222  97.421738  0.0  59.0  128.0  195.00  370.0
NA          23.0   24.521739  28.266378  1.0   5.0   11.0   34.00  100.0
OC          16.0   35.625000  64.555790  0.0   1.0    8.5   23.25  212.0
SA          12.0   62.416667  88.620189  1.0   3.0   12.0   98.50  221.0

### Step 6. Print the mean alcohol consumption per continent for every column

In [ ]:
df.groupby("continent").mean(numeric_only= True)

,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol
continent,,,,
AF,61.471698,16.339623,16.264151,3.007547
AS,37.045455,60.840909,9.068182,2.170455
EU,193.777778,132.555556,142.222222,8.617778
NA,145.434783,165.739130,24.521739,5.995652
OC,89.687500,58.437500,35.625000,3.381250
SA,175.083333,114.750000,62.416667,6.308333

### Step 7. Print the median alcohol consumption per continent for every column

In [32]:
df.groupby("continent").median(numeric_only= True)

,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol
continent,,,,
AF,32.0,3.0,2.0,2.30
AS,17.5,16.0,1.0,1.20
EU,219.0,122.0,128.0,10.00
NA,143.0,137.0,11.0,6.30
OC,52.5,37.0,8.5,1.75
SA,162.5,108.5,12.0,6.85

### Step 8. Print the mean, min and max values for spirit consumption per continent.

In [35]:
df.groupby("continent")["spirit_servings"].aggregate(["min", "mean", "max"])

           min        mean  max
continent
AF           0   16.339623  152
AS           0   60.840909  326
EU           0  132.555556  373
NA          68  165.739130  438
OC           0   58.437500  254
SA          25  114.750000  302